// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { ObjectType, Field, Int } from '@nestjs/graphql';

@ObjectType({ description: undefined })
export class AffectedRowsOutput {
  @Field(() => Int, { nullable: false, description: undefined })
  count!: number;
}
