// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { ObjectType, Field, Int } from '@nestjs/graphql';

@ObjectType({ description: undefined })
export class UserCountOutputType {
  @Field(() => Int, { nullable: false, description: undefined })
  posts!: number;
  @Field(() => Int, { nullable: false, description: undefined })
  children!: number;
  @Field(() => Int, { nullable: false, description: undefined })
  anotherPosts!: number;
}
