// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { UserWhereUniqueInput } from './user-where-unique.input';
import { Type } from 'class-transformer';
import { Prisma } from '../../../@prisma-client';
import { UserCreateWithoutChildrenInput } from './user-create-without-children.input';

@InputType()
export class UserCreateOrConnectWithoutChildrenInput {
  @Type(() => UserWhereUniqueInput)
  @Field(() => UserWhereUniqueInput, {
    nullable: false,
    description: undefined,
  })
  where!: Prisma.AtLeast<UserWhereUniqueInput, 'id' | 'email'>;
  @Type(() => UserCreateWithoutChildrenInput)
  @Field(() => UserCreateWithoutChildrenInput, {
    nullable: false,
    description: undefined,
  })
  create!: UserCreateWithoutChildrenInput;
}
