// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { InputType, Field, HideField } from '@nestjs/graphql';
import { UserCreateWithoutChildrenInput } from './user-create-without-children.input';
import { Type } from 'class-transformer';
import { UserCreateOrConnectWithoutChildrenInput } from './user-create-or-connect-without-children.input';
import { UserUpsertWithoutChildrenInput } from './user-upsert-without-children.input';
import { UserWhereInput } from './user-where.input';
import { UserWhereUniqueInput } from './user-where-unique.input';
import { Prisma } from '../../../@prisma-client';
import { UserUpdateToOneWithWhereWithoutChildrenInput } from './user-update-to-one-with-where-without-children.input';

@InputType()
export class UserUpdateOneWithoutChildrenNestedInput {
  @Type(() => UserCreateWithoutChildrenInput)
  @Field(() => UserCreateWithoutChildrenInput, {
    nullable: true,
    description: undefined,
  })
  create?: UserCreateWithoutChildrenInput | null;
  @Type(() => UserCreateOrConnectWithoutChildrenInput)
  @HideField()
  connectOrCreate?: UserCreateOrConnectWithoutChildrenInput | null;
  @Type(() => UserUpsertWithoutChildrenInput)
  @HideField()
  upsert?: UserUpsertWithoutChildrenInput | null;
  @Type(() => UserWhereInput)
  @Field(() => UserWhereInput, { nullable: true, description: undefined })
  disconnect?: UserWhereInput | null;
  @Type(() => UserWhereInput)
  @Field(() => UserWhereInput, { nullable: true, description: undefined })
  delete?: UserWhereInput | null;
  @Type(() => UserWhereUniqueInput)
  @Field(() => UserWhereUniqueInput, { nullable: true, description: undefined })
  connect?: Prisma.AtLeast<UserWhereUniqueInput, 'id' | 'email'>;
  @Type(() => UserUpdateToOneWithWhereWithoutChildrenInput)
  @Field(() => UserUpdateToOneWithWhereWithoutChildrenInput, {
    nullable: true,
    description: undefined,
  })
  update?: UserUpdateToOneWithWhereWithoutChildrenInput | null;
}
