// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { ArgsType, Field } from '@nestjs/graphql';
import { StandaloneModelCreateInput } from '../input/standalone-model-create.input';
import { Type } from 'class-transformer';

@ArgsType()
export class StandaloneModelCreateArgs {
  @Type(() => StandaloneModelCreateInput)
  @Field(() => StandaloneModelCreateInput, {
    nullable: false,
    description: undefined,
  })
  data!: StandaloneModelCreateInput;
}
