// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { ArgsType, Field } from '@nestjs/graphql';
import { StandaloneModelWhereUniqueInput } from '../input/standalone-model-where-unique.input';
import { Type } from 'class-transformer';
import { Prisma } from '../../../@prisma-client';

@ArgsType()
export class StandaloneModelFindUniqueArgs {
  @Type(() => StandaloneModelWhereUniqueInput)
  @Field(() => StandaloneModelWhereUniqueInput, { nullable: false, description: undefined })
  where!: Prisma.AtLeast<StandaloneModelWhereUniqueInput, 'id'>;
}
