// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { ArgsType, Field, Int } from '@nestjs/graphql';
import { StandaloneModelWhereInput } from '../input/standalone-model-where.input';
import { Type } from 'class-transformer';
import { StandaloneModelOrderByWithRelationInput } from '../input/standalone-model-order-by-with-relation.input';
import { StandaloneModelWhereUniqueInput } from '../input/standalone-model-where-unique.input';
import { Prisma } from '../../../@prisma-client';
import { StandaloneModelScalarFieldEnum } from '../enum/standalone-model-scalar-field.enum';

@ArgsType()
export class StandaloneModelFindManyArgs {
  @Type(() => StandaloneModelWhereInput)
  @Field(() => StandaloneModelWhereInput, {
    nullable: true,
    description: undefined,
  })
  where?: Omit<StandaloneModelWhereInput, never> | null;
  @Type(() => StandaloneModelOrderByWithRelationInput)
  @Field(() => [StandaloneModelOrderByWithRelationInput], {
    nullable: true,
    description: undefined,
  })
  orderBy?: Array<StandaloneModelOrderByWithRelationInput> | null;
  @Type(() => StandaloneModelWhereUniqueInput)
  @Field(() => StandaloneModelWhereUniqueInput, {
    nullable: true,
    description: undefined,
  })
  cursor?: Prisma.AtLeast<StandaloneModelWhereUniqueInput, 'id'>;
  @Field(() => Int, { nullable: true, description: undefined })
  take?: number | null;
  @Field(() => Int, { nullable: true, description: undefined })
  skip?: number | null;
  @Field(() => [StandaloneModelScalarFieldEnum], {
    nullable: true,
    description: undefined,
  })
  distinct?: Array<keyof typeof StandaloneModelScalarFieldEnum> | null;
}
