// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { ArgsType, Field } from '@nestjs/graphql';
import { StandaloneModelCreateManyInput } from '../input/standalone-model-create-many.input';
import { Type } from 'class-transformer';

@ArgsType()
export class StandaloneModelCreateManyArgs {
  @Type(() => StandaloneModelCreateManyInput)
  @Field(() => [StandaloneModelCreateManyInput], { nullable: false, description: undefined })
  data!: Array<StandaloneModelCreateManyInput>;
  @Field(() => Boolean, { nullable: true, description: undefined })
  skipDuplicates?: boolean | null;
}
