// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { ObjectType, Field, Int } from '@nestjs/graphql';

@ObjectType({ description: undefined })
export class CategoryMetadata {
  @Field(() => Int, { nullable: false, description: undefined })
  id!: number;
  @Field(() => Int, { nullable: false, description: undefined })
  categoryId!: number;
  @Field(() => Date, { nullable: false, description: undefined })
  createdAt!: Date | string;
  @Field(() => Date, { nullable: false, description: undefined })
  updatedAt!: Date | string;
}
