// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { ArgsType, Field } from '@nestjs/graphql';
import { StandaloneCreateManyInput } from '../input/standalone-create-many.input';
import { Type } from 'class-transformer';

@ArgsType()
export class StandaloneCreateManyArgs {
  @Type(() => StandaloneCreateManyInput)
  @Field(() => [StandaloneCreateManyInput], {
    nullable: false,
    description: undefined,
  })
  data!: Array<StandaloneCreateManyInput>;
  @Field(() => Boolean, { nullable: true, description: undefined })
  skipDuplicates?: boolean | null;
}
