// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { ArgsType, Field } from '@nestjs/graphql';
import { StandaloneUpdateInput } from '../input/standalone-update.input';
import { Type } from 'class-transformer';
import { StandaloneWhereUniqueInput } from '../input/standalone-where-unique.input';
import { Prisma } from '../../../@prisma-client';

@ArgsType()
export class StandaloneUpdateArgs {
  @Type(() => StandaloneUpdateInput)
  @Field(() => StandaloneUpdateInput, {
    nullable: false,
    description: undefined,
  })
  data!: StandaloneUpdateInput;
  @Type(() => StandaloneWhereUniqueInput)
  @Field(() => StandaloneWhereUniqueInput, {
    nullable: false,
    description: undefined,
  })
  where!: Prisma.AtLeast<StandaloneWhereUniqueInput, 'id'>;
}
