// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { registerEnumType } from '@nestjs/graphql';

export enum QueryMode {
  'default' = 'default',
  insensitive = 'insensitive'
}

registerEnumType(QueryMode, { name: 'QueryMode', description: undefined, valuesMap: undefined })
