// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { registerEnumType } from '@nestjs/graphql';

export enum PostScalarFieldEnum {
  id = 'id',
  title = 'title',
  content = 'content',
  published = 'published',
  authorId = 'authorId',
  anotherAuthorId = 'anotherAuthorId',
  createdAt = 'createdAt',
  updatedAt = 'updatedAt',
  postKind = 'postKind',
  jsonField = 'jsonField',
  scalarList = 'scalarList',
}

registerEnumType(PostScalarFieldEnum, {
  name: 'PostScalarFieldEnum',
  description: undefined,
  valuesMap: undefined,
});
