// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { registerEnumType } from '@nestjs/graphql';

/** UserRole Documentation */
export enum UserRole {
  /** UserRole USER */
  USER = 'USER',
  /** UserRole ADMIN */
  ADMIN = 'ADMIN',
  /** UserRole MODERATOR */
  MODERATOR = 'MODERATOR',
}

registerEnumType(UserRole, {
  name: 'UserRole',
  description: 'UserRole Documentation',
  valuesMap: {
    USER: { description: 'UserRole USER' },
    ADMIN: { description: 'UserRole ADMIN' },
    MODERATOR: { description: 'UserRole MODERATOR' },
  },
});
