// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { Type } from 'class-transformer';
import { IntFilter } from '../../../prisma/base/input/int-filter.input';
import { DateTimeFilter } from '../../../prisma/base/input/date-time-filter.input';
import { StringFilter } from '../../../prisma/base/input/string-filter.input';
import { JsonFilter } from '../../../prisma/base/input/json-filter.input';
import { StringNullableListFilter } from '../../../prisma/base/input/string-nullable-list-filter.input';

@InputType()
export class StandaloneWhereInput {
  @Type(() => StandaloneWhereInput)
  @Field(() => [StandaloneWhereInput], {
    nullable: true,
    description: undefined,
  })
  AND?: Array<StandaloneWhereInput> | null;
  @Type(() => StandaloneWhereInput)
  @Field(() => [StandaloneWhereInput], {
    nullable: true,
    description: undefined,
  })
  OR?: Array<StandaloneWhereInput> | null;
  @Type(() => StandaloneWhereInput)
  @Field(() => [StandaloneWhereInput], {
    nullable: true,
    description: undefined,
  })
  NOT?: Array<StandaloneWhereInput> | null;
  @Type(() => IntFilter)
  @Field(() => IntFilter, { nullable: true, description: undefined })
  id?: IntFilter | null;
  @Type(() => DateTimeFilter)
  @Field(() => DateTimeFilter, { nullable: true, description: undefined })
  createdAt?: DateTimeFilter | null;
  @Type(() => DateTimeFilter)
  @Field(() => DateTimeFilter, { nullable: true, description: undefined })
  updatedAt?: DateTimeFilter | null;
  @Type(() => StringFilter)
  @Field(() => StringFilter, { nullable: true, description: undefined })
  name?: StringFilter | null;
  @Type(() => JsonFilter)
  @Field(() => JsonFilter, { nullable: true, description: undefined })
  jsonField?: JsonFilter | null;
  @Type(() => StringNullableListFilter)
  @Field(() => StringNullableListFilter, {
    nullable: true,
    description: undefined,
  })
  scalarList?: StringNullableListFilter | null;
}
