// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field, Int } from '@nestjs/graphql';
import { GraphQLJSON, GraphQLByte, GraphQLBigInt } from 'graphql-scalars';
import type { JsonValue } from 'type-fest';
import { StandaloneCreatestringListInput } from './standalone-createstring-list.input';
import { Type, Transform } from 'class-transformer';
import {
  GraphQLDecimal,
  transformToDecimal,
} from 'prisma-graphql-type-decimal';
import { Decimal } from '@prisma/client/runtime/library';

@InputType()
export class StandaloneCreateManyInput {
  @Field(() => Int, { nullable: true, description: undefined })
  id?: number | null;
  @Field(() => Date, { nullable: true, description: undefined })
  createdAt?: Date | string | null;
  @Field(() => Date, { nullable: true, description: undefined })
  updatedAt?: Date | string | null;
  @Field(() => String, { nullable: false, description: undefined })
  name!: string;
  @Field(() => GraphQLJSON, { nullable: false, description: undefined })
  jsonField!: JsonValue;
  @Type(() => StandaloneCreatestringListInput)
  @Field(() => StandaloneCreatestringListInput, {
    nullable: true,
    description: undefined,
  })
  stringList?: StandaloneCreatestringListInput | null;
  @Type(() => Object)
  @Transform(transformToDecimal)
  @Field(() => GraphQLDecimal, { nullable: false, description: undefined })
  decimalField!: Decimal;
  @Field(() => Number, { nullable: false, description: undefined })
  floatField!: number;
  @Field(() => GraphQLByte, { nullable: false, description: undefined })
  bytesField!: Buffer;
  @Field(() => GraphQLBigInt, { nullable: false, description: undefined })
  bigIntField!: bigint | number;
  @Field(() => Date, { nullable: false, description: undefined })
  dateTimeField!: Date | string;
}
