// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { DateTimeFieldUpdateOperationsInput } from '../../../prisma/base/input/date-time-field-update-operations.input';
import { Type } from 'class-transformer';
import { StringFieldUpdateOperationsInput } from '../../../prisma/base/input/string-field-update-operations.input';
import { GraphQLJSON } from 'graphql-scalars';
import type { JsonValue } from 'type-fest';
import { StandaloneUpdatestringListInput } from './standalone-updatestring-list.input';
import { DecimalFieldUpdateOperationsInput } from '../../../prisma/base/input/decimal-field-update-operations.input';
import { FloatFieldUpdateOperationsInput } from '../../../prisma/base/input/float-field-update-operations.input';
import { BytesFieldUpdateOperationsInput } from '../../../prisma/base/input/bytes-field-update-operations.input';
import { BigIntFieldUpdateOperationsInput } from '../../../prisma/base/input/big-int-field-update-operations.input';

@InputType()
export class StandaloneUpdateInput {
  @Type(() => DateTimeFieldUpdateOperationsInput)
  @Field(() => DateTimeFieldUpdateOperationsInput, {
    nullable: true,
    description: undefined,
  })
  createdAt?: DateTimeFieldUpdateOperationsInput | null;
  @Type(() => DateTimeFieldUpdateOperationsInput)
  @Field(() => DateTimeFieldUpdateOperationsInput, {
    nullable: true,
    description: undefined,
  })
  updatedAt?: DateTimeFieldUpdateOperationsInput | null;
  @Type(() => StringFieldUpdateOperationsInput)
  @Field(() => StringFieldUpdateOperationsInput, {
    nullable: true,
    description: undefined,
  })
  name?: StringFieldUpdateOperationsInput | null;
  @Field(() => GraphQLJSON, { nullable: true, description: undefined })
  jsonField?: JsonValue | null;
  @Type(() => StandaloneUpdatestringListInput)
  @Field(() => StandaloneUpdatestringListInput, {
    nullable: true,
    description: undefined,
  })
  stringList?: StandaloneUpdatestringListInput | null;
  @Type(() => DecimalFieldUpdateOperationsInput)
  @Field(() => DecimalFieldUpdateOperationsInput, {
    nullable: true,
    description: undefined,
  })
  decimalField?: DecimalFieldUpdateOperationsInput | null;
  @Type(() => FloatFieldUpdateOperationsInput)
  @Field(() => FloatFieldUpdateOperationsInput, {
    nullable: true,
    description: undefined,
  })
  floatField?: FloatFieldUpdateOperationsInput | null;
  @Type(() => BytesFieldUpdateOperationsInput)
  @Field(() => BytesFieldUpdateOperationsInput, {
    nullable: true,
    description: undefined,
  })
  bytesField?: BytesFieldUpdateOperationsInput | null;
  @Type(() => BigIntFieldUpdateOperationsInput)
  @Field(() => BigIntFieldUpdateOperationsInput, {
    nullable: true,
    description: undefined,
  })
  bigIntField?: BigIntFieldUpdateOperationsInput | null;
  @Type(() => DateTimeFieldUpdateOperationsInput)
  @Field(() => DateTimeFieldUpdateOperationsInput, {
    nullable: true,
    description: undefined,
  })
  dateTimeField?: DateTimeFieldUpdateOperationsInput | null;
}
