// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { registerEnumType } from '@nestjs/graphql';

export enum CategoryMetadataScalarFieldEnum {
  id = 'id',
  categoryId = 'categoryId',
  createdAt = 'createdAt',
  updatedAt = 'updatedAt',
  metadata = 'metadata'
}

registerEnumType(CategoryMetadataScalarFieldEnum, { name: 'CategoryMetadataScalarFieldEnum', description: undefined, valuesMap: undefined })
