// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { ArgsType, Field } from '@nestjs/graphql';
import { PostUpdateManyMutationInput } from '../input/post-update-many-mutation.input';
import { Type } from 'class-transformer';
import { PostWhereInput } from '../input/post-where.input';

@ArgsType()
export class PostUpdateManyArgs {
  @Type(() => PostUpdateManyMutationInput)
  @Field(() => PostUpdateManyMutationInput, { nullable: false, description: undefined })
  data!: PostUpdateManyMutationInput;
  @Type(() => PostWhereInput)
  @Field(() => PostWhereInput, { nullable: true, description: undefined })
  where?: PostWhereInput | null;
}
