// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { ArgsType, Field } from '@nestjs/graphql';
import { PostCreateManyInput } from '../input/post-create-many.input';
import { Type } from 'class-transformer';

@ArgsType()
export class PostCreateManyArgs {
  @Type(() => PostCreateManyInput)
  @Field(() => [PostCreateManyInput], { nullable: false, description: undefined })
  data!: Array<PostCreateManyInput>;
  @Field(() => Boolean, { nullable: true, description: undefined })
  skipDuplicates?: boolean | null;
}
