// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { ArgsType, Field } from '@nestjs/graphql';
import { PostUpdateInput } from '../input/post-update.input';
import { Type } from 'class-transformer';
import { PostWhereUniqueInput } from '../input/post-where-unique.input';
import { Prisma } from '../../../@prisma-client';

@ArgsType()
export class PostUpdateArgs {
  @Type(() => PostUpdateInput)
  @Field(() => PostUpdateInput, { nullable: false, description: undefined })
  data!: PostUpdateInput;
  @Type(() => PostWhereUniqueInput)
  @Field(() => PostWhereUniqueInput, { nullable: false, description: undefined })
  where!: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
}
