// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { registerEnumType } from '@nestjs/graphql';

export enum CategoryScalarFieldEnum {
  id = 'id',
  name = 'name',
  createdAt = 'createdAt',
  updatedAt = 'updatedAt'
}

registerEnumType(CategoryScalarFieldEnum, { name: 'CategoryScalarFieldEnum', description: undefined, valuesMap: undefined })
