// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field } from '@nestjs/graphql';
import { Type } from 'class-transformer';
import { IntFilter } from './int-filter.input';
import { DateTimeFilter } from './date-time-filter.input';
import { CategoryRelationFilter } from './category-relation-filter.input';

@InputType()
export class CategoryMetadataWhereInput {
  @Type(() => CategoryMetadataWhereInput)
  @Field(() => [CategoryMetadataWhereInput], {
    nullable: true,
    description: undefined,
  })
  AND?: Array<CategoryMetadataWhereInput> | null;
  @Type(() => CategoryMetadataWhereInput)
  @Field(() => [CategoryMetadataWhereInput], {
    nullable: true,
    description: undefined,
  })
  OR?: Array<CategoryMetadataWhereInput> | null;
  @Type(() => CategoryMetadataWhereInput)
  @Field(() => [CategoryMetadataWhereInput], {
    nullable: true,
    description: undefined,
  })
  NOT?: Array<CategoryMetadataWhereInput> | null;
  @Type(() => IntFilter)
  @Field(() => IntFilter, { nullable: true, description: undefined })
  id?: IntFilter | null;
  @Type(() => IntFilter)
  @Field(() => IntFilter, { nullable: true, description: undefined })
  categoryId?: IntFilter | null;
  @Type(() => DateTimeFilter)
  @Field(() => DateTimeFilter, { nullable: true, description: undefined })
  createdAt?: DateTimeFilter | null;
  @Type(() => DateTimeFilter)
  @Field(() => DateTimeFilter, { nullable: true, description: undefined })
  updatedAt?: DateTimeFilter | null;
  @Type(() => CategoryRelationFilter)
  @Field(() => CategoryRelationFilter, {
    nullable: true,
    description: undefined,
  })
  category?: CategoryRelationFilter | null;
}
