// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field } from '@nestjs/graphql';
import { SortOrder } from '../enum';
import { CategoryOrderByWithRelationInput } from './category-order-by-with-relation.input';
import { Type } from 'class-transformer';

@InputType()
export class CategoryMetadataOrderByWithRelationInput {
  @Field(() => SortOrder, { nullable: true, description: undefined })
  id?: keyof typeof SortOrder;
  @Field(() => SortOrder, { nullable: true, description: undefined })
  categoryId?: keyof typeof SortOrder;
  @Field(() => SortOrder, { nullable: true, description: undefined })
  createdAt?: keyof typeof SortOrder;
  @Field(() => SortOrder, { nullable: true, description: undefined })
  updatedAt?: keyof typeof SortOrder;
  @Type(() => CategoryOrderByWithRelationInput)
  @Field(() => CategoryOrderByWithRelationInput, {
    nullable: true,
    description: undefined,
  })
  category?: Omit<CategoryOrderByWithRelationInput, never>;
}
