// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field } from '@nestjs/graphql';
import { Type } from 'class-transformer';
import { IntFilter } from './int-filter.input';
import { StringFilter } from './string-filter.input';
import { DateTimeFilter } from './date-time-filter.input';
import { PostListRelationFilter } from './post-list-relation-filter.input';
import { CategoryMetadataNullableRelationFilter } from './category-metadata-nullable-relation-filter.input';

@InputType()
export class CategoryWhereInput {
  @Type(() => CategoryWhereInput)
  @Field(() => [CategoryWhereInput], { nullable: true, description: undefined })
  AND?: Array<CategoryWhereInput>;
  @Type(() => CategoryWhereInput)
  @Field(() => [CategoryWhereInput], { nullable: true, description: undefined })
  OR?: Array<CategoryWhereInput>;
  @Type(() => CategoryWhereInput)
  @Field(() => [CategoryWhereInput], { nullable: true, description: undefined })
  NOT?: Array<CategoryWhereInput>;
  @Type(() => IntFilter)
  @Field(() => IntFilter, { nullable: true, description: undefined })
  id?: IntFilter;
  @Type(() => StringFilter)
  @Field(() => StringFilter, { nullable: true, description: undefined })
  name?: StringFilter;
  @Type(() => DateTimeFilter)
  @Field(() => DateTimeFilter, { nullable: true, description: undefined })
  createdAt?: DateTimeFilter;
  @Type(() => DateTimeFilter)
  @Field(() => DateTimeFilter, { nullable: true, description: undefined })
  updatedAt?: DateTimeFilter;
  @Type(() => PostListRelationFilter)
  @Field(() => PostListRelationFilter, {
    nullable: true,
    description: undefined,
  })
  posts?: Omit<PostListRelationFilter, never>;
  @Type(() => CategoryMetadataNullableRelationFilter)
  @Field(() => CategoryMetadataNullableRelationFilter, {
    nullable: true,
    description: undefined,
  })
  metadata?: CategoryMetadataNullableRelationFilter;
}
