// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field } from '@nestjs/graphql';
import { CategoryWhereUniqueInput } from './category-where-unique.input';
import { Type } from 'class-transformer';
import { Prisma } from '../../../prisma-client';
import { CategoryCreateWithoutMetadataInput } from './category-create-without-metadata.input';

@InputType()
export class CategoryCreateOrConnectWithoutMetadataInput {
  @Type(() => CategoryWhereUniqueInput)
  @Field(() => CategoryWhereUniqueInput, {
    nullable: false,
    description: undefined,
  })
  where!: Prisma.AtLeast<CategoryWhereUniqueInput, 'id' | 'name'>;
  @Type(() => CategoryCreateWithoutMetadataInput)
  @Field(() => CategoryCreateWithoutMetadataInput, {
    nullable: false,
    description: undefined,
  })
  create!: CategoryCreateWithoutMetadataInput;
}
