// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field, HideField } from '@nestjs/graphql';
import { CategoryCreateWithoutMetadataInput } from './category-create-without-metadata.input';
import { Type } from 'class-transformer';
import { CategoryCreateOrConnectWithoutMetadataInput } from './category-create-or-connect-without-metadata.input';
import { CategoryWhereUniqueInput } from './category-where-unique.input';
import { Prisma } from '../../../prisma-client';

@InputType()
export class CategoryCreateNestedOneWithoutMetadataInput {
  @Type(() => CategoryCreateWithoutMetadataInput)
  @Field(() => CategoryCreateWithoutMetadataInput, {
    nullable: true,
    description: undefined,
  })
  create?: CategoryCreateWithoutMetadataInput | null;
  @Type(() => CategoryCreateOrConnectWithoutMetadataInput)
  @HideField()
  connectOrCreate?: CategoryCreateOrConnectWithoutMetadataInput | null;
  @Type(() => CategoryWhereUniqueInput)
  @Field(() => CategoryWhereUniqueInput, {
    nullable: true,
    description: undefined,
  })
  connect?: Prisma.AtLeast<CategoryWhereUniqueInput, 'id' | 'name'>;
}
