// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field } from '@nestjs/graphql';
import { SortOrder } from '../enum';

@InputType()
export class CategoryOrderByRelationAggregateInput {
  @Field(() => SortOrder, { nullable: true, description: undefined })
  _count?: keyof typeof SortOrder;
}
