// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field } from '@nestjs/graphql';
import { CategoryMetadataWhereInput } from './category-metadata-where.input';
import { Type } from 'class-transformer';

@InputType()
export class CategoryMetadataNullableRelationFilter {
  @Type(() => CategoryMetadataWhereInput)
  @Field(() => CategoryMetadataWhereInput, {
    nullable: true,
    description: undefined,
  })
  is?: Omit<CategoryMetadataWhereInput, never> | null;
  @Type(() => CategoryMetadataWhereInput)
  @Field(() => CategoryMetadataWhereInput, {
    nullable: true,
    description: undefined,
  })
  isNot?: Omit<CategoryMetadataWhereInput, never> | null;
}
