// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field, HideField } from '@nestjs/graphql';
import { PostCreateWithoutAuthorInput } from './post-create-without-author.input';
import { Type } from 'class-transformer';
import { PostCreateOrConnectWithoutAuthorInput } from './post-create-or-connect-without-author.input';
import { PostUpsertWithWhereUniqueWithoutAuthorInput } from './post-upsert-with-where-unique-without-author.input';
import { PostCreateManyAuthorInputEnvelope } from './post-create-many-author-input-envelope.input';
import { PostWhereUniqueInput } from './post-where-unique.input';
import { Prisma } from '../../../prisma-client';
import { PostUpdateWithWhereUniqueWithoutAuthorInput } from './post-update-with-where-unique-without-author.input';
import { PostUpdateManyWithWhereWithoutAuthorInput } from './post-update-many-with-where-without-author.input';
import { PostScalarWhereInput } from './post-scalar-where.input';

@InputType()
export class PostUpdateManyWithoutAuthorNestedInput {
  @Type(() => PostCreateWithoutAuthorInput)
  @Field(() => [PostCreateWithoutAuthorInput], {
    nullable: true,
    description: undefined,
  })
  create?: Array<PostCreateWithoutAuthorInput> | null;
  @Type(() => PostCreateOrConnectWithoutAuthorInput)
  @HideField()
  connectOrCreate?: Array<PostCreateOrConnectWithoutAuthorInput> | null;
  @Type(() => PostUpsertWithWhereUniqueWithoutAuthorInput)
  @HideField()
  upsert?: Array<PostUpsertWithWhereUniqueWithoutAuthorInput> | null;
  @Type(() => PostCreateManyAuthorInputEnvelope)
  @HideField()
  createMany?: PostCreateManyAuthorInputEnvelope | null;
  @Type(() => PostWhereUniqueInput)
  @HideField()
  set?: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostWhereUniqueInput)
  @Field(() => [PostWhereUniqueInput], {
    nullable: true,
    description: undefined,
  })
  disconnect?: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostWhereUniqueInput)
  @Field(() => [PostWhereUniqueInput], {
    nullable: true,
    description: undefined,
  })
  delete?: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostWhereUniqueInput)
  @Field(() => [PostWhereUniqueInput], {
    nullable: true,
    description: undefined,
  })
  connect?: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostUpdateWithWhereUniqueWithoutAuthorInput)
  @Field(() => [PostUpdateWithWhereUniqueWithoutAuthorInput], {
    nullable: true,
    description: undefined,
  })
  update?: Array<PostUpdateWithWhereUniqueWithoutAuthorInput> | null;
  @Type(() => PostUpdateManyWithWhereWithoutAuthorInput)
  @HideField()
  updateMany?: Array<PostUpdateManyWithWhereWithoutAuthorInput> | null;
  @Type(() => PostScalarWhereInput)
  @HideField()
  deleteMany?: Array<PostScalarWhereInput> | null;
}
