// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field, Int } from '@nestjs/graphql';
import { PostWhereInput } from './post-where.input';
import { Type } from 'class-transformer';
import { StringFilter } from './string-filter.input';
import { StringNullableFilter } from './string-nullable-filter.input';
import { BoolFilter } from './bool-filter.input';
import { IntFilter } from './int-filter.input';
import { DateTimeFilter } from './date-time-filter.input';
import { EnumPostKindFilter } from './enum-post-kind-filter.input';
import { JsonFilter } from './json-filter.input';
import { StringNullableListFilter } from './string-nullable-list-filter.input';
import { UserRelationFilter } from './user-relation-filter.input';
import { CategoryListRelationFilter } from './category-list-relation-filter.input';

@InputType()
export class PostWhereUniqueInput {
  @Field(() => Int, { nullable: true, description: undefined })
  id?: number | null;
  @Type(() => PostWhereInput)
  @Field(() => [PostWhereInput], { nullable: true, description: undefined })
  AND?: Array<PostWhereInput> | null;
  @Type(() => PostWhereInput)
  @Field(() => [PostWhereInput], { nullable: true, description: undefined })
  OR?: Array<PostWhereInput> | null;
  @Type(() => PostWhereInput)
  @Field(() => [PostWhereInput], { nullable: true, description: undefined })
  NOT?: Array<PostWhereInput> | null;
  @Type(() => StringFilter)
  @Field(() => StringFilter, { nullable: true, description: undefined })
  title?: StringFilter | null;
  @Type(() => StringNullableFilter)
  @Field(() => StringNullableFilter, { nullable: true, description: undefined })
  content?: StringNullableFilter | null;
  @Type(() => BoolFilter)
  @Field(() => BoolFilter, { nullable: true, description: undefined })
  published?: BoolFilter | null;
  @Type(() => IntFilter)
  @Field(() => IntFilter, { nullable: true, description: undefined })
  authorId?: IntFilter | null;
  @Type(() => IntFilter)
  @Field(() => IntFilter, { nullable: true, description: undefined })
  anotherAuthorId?: IntFilter | null;
  @Type(() => DateTimeFilter)
  @Field(() => DateTimeFilter, { nullable: true, description: undefined })
  createdAt?: DateTimeFilter | null;
  @Type(() => DateTimeFilter)
  @Field(() => DateTimeFilter, { nullable: true, description: undefined })
  updatedAt?: DateTimeFilter | null;
  @Type(() => EnumPostKindFilter)
  @Field(() => EnumPostKindFilter, { nullable: true, description: undefined })
  postKind?: EnumPostKindFilter | null;
  @Type(() => JsonFilter)
  @Field(() => JsonFilter, { nullable: true, description: undefined })
  jsonField?: JsonFilter | null;
  @Type(() => StringNullableListFilter)
  @Field(() => StringNullableListFilter, {
    nullable: true,
    description: undefined,
  })
  scalarList?: StringNullableListFilter | null;
  @Type(() => UserRelationFilter)
  @Field(() => UserRelationFilter, { nullable: true, description: undefined })
  author?: UserRelationFilter | null;
  @Type(() => UserRelationFilter)
  @Field(() => UserRelationFilter, { nullable: true, description: undefined })
  anotherAuthor?: UserRelationFilter | null;
  @Type(() => CategoryListRelationFilter)
  @Field(() => CategoryListRelationFilter, {
    nullable: true,
    description: undefined,
  })
  categories?: Omit<CategoryListRelationFilter, never> | null;
}
