// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field } from '@nestjs/graphql';
import { PostWhereUniqueInput } from './post-where-unique.input';
import { Type } from 'class-transformer';
import { Prisma } from '../../../@prisma-client';
import { PostUpdateWithoutAuthorInput } from './post-update-without-author.input';

@InputType()
export class PostUpdateWithWhereUniqueWithoutAuthorInput {
  @Type(() => PostWhereUniqueInput)
  @Field(() => PostWhereUniqueInput, {
    nullable: false,
    description: undefined,
  })
  where!: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostUpdateWithoutAuthorInput)
  @Field(() => PostUpdateWithoutAuthorInput, {
    nullable: false,
    description: undefined,
  })
  data!: PostUpdateWithoutAuthorInput;
}
