// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field } from '@nestjs/graphql';
import { PostCreateWithoutCategoriesInput } from './post-create-without-categories.input';
import { Type } from 'class-transformer';
import { PostCreateOrConnectWithoutCategoriesInput } from './post-create-or-connect-without-categories.input';
import { PostUpsertWithWhereUniqueWithoutCategoriesInput } from './post-upsert-with-where-unique-without-categories.input';
import { PostWhereUniqueInput } from './post-where-unique.input';
import { Prisma } from '../../../prisma-client';
import { PostUpdateWithWhereUniqueWithoutCategoriesInput } from './post-update-with-where-unique-without-categories.input';
import { PostUpdateManyWithWhereWithoutCategoriesInput } from './post-update-many-with-where-without-categories.input';
import { PostScalarWhereInput } from './post-scalar-where.input';

@InputType()
export class PostUpdateManyWithoutCategoriesNestedInput {
  @Type(() => PostCreateWithoutCategoriesInput)
  @Field(() => [PostCreateWithoutCategoriesInput], {
    nullable: true,
    description: undefined,
  })
  create?: Array<PostCreateWithoutCategoriesInput>;
  @Type(() => PostCreateOrConnectWithoutCategoriesInput)
  @Field(() => [PostCreateOrConnectWithoutCategoriesInput], {
    nullable: true,
    description: undefined,
  })
  connectOrCreate?: Array<PostCreateOrConnectWithoutCategoriesInput>;
  @Type(() => PostUpsertWithWhereUniqueWithoutCategoriesInput)
  @Field(() => [PostUpsertWithWhereUniqueWithoutCategoriesInput], {
    nullable: true,
    description: undefined,
  })
  upsert?: Array<PostUpsertWithWhereUniqueWithoutCategoriesInput>;
  @Type(() => PostWhereUniqueInput)
  @Field(() => [PostWhereUniqueInput], {
    nullable: true,
    description: undefined,
  })
  set?: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostWhereUniqueInput)
  @Field(() => [PostWhereUniqueInput], {
    nullable: true,
    description: undefined,
  })
  disconnect?: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostWhereUniqueInput)
  @Field(() => [PostWhereUniqueInput], {
    nullable: true,
    description: undefined,
  })
  delete?: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostWhereUniqueInput)
  @Field(() => [PostWhereUniqueInput], {
    nullable: true,
    description: undefined,
  })
  connect?: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostUpdateWithWhereUniqueWithoutCategoriesInput)
  @Field(() => [PostUpdateWithWhereUniqueWithoutCategoriesInput], {
    nullable: true,
    description: undefined,
  })
  update?: Array<PostUpdateWithWhereUniqueWithoutCategoriesInput>;
  @Type(() => PostUpdateManyWithWhereWithoutCategoriesInput)
  @Field(() => [PostUpdateManyWithWhereWithoutCategoriesInput], {
    nullable: true,
    description: undefined,
  })
  updateMany?: Array<PostUpdateManyWithWhereWithoutCategoriesInput>;
  @Type(() => PostScalarWhereInput)
  @Field(() => [PostScalarWhereInput], {
    nullable: true,
    description: undefined,
  })
  deleteMany?: Array<PostScalarWhereInput>;
}
