// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field } from '@nestjs/graphql';
import { PostWhereUniqueInput } from './post-where-unique.input';
import { Type } from 'class-transformer';
import { Prisma } from '../../../@prisma-client';
import { PostCreateWithoutAuthorInput } from './post-create-without-author.input';

@InputType()
export class PostCreateOrConnectWithoutAuthorInput {
  @Type(() => PostWhereUniqueInput)
  @Field(() => PostWhereUniqueInput, {
    nullable: false,
    description: undefined,
  })
  where!: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostCreateWithoutAuthorInput)
  @Field(() => PostCreateWithoutAuthorInput, {
    nullable: false,
    description: undefined,
  })
  create!: PostCreateWithoutAuthorInput;
}
