// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field, Int } from '@nestjs/graphql';
import { StandaloneWhereInput } from './standalone-where.input';
import { Type } from 'class-transformer';
import { DateTimeFilter } from './date-time-filter.input';
import { StringFilter } from './string-filter.input';
import { JsonFilter } from './json-filter.input';
import { StringNullableListFilter } from './string-nullable-list-filter.input';

@InputType()
export class StandaloneWhereUniqueInput {
  @Field(() => Int, { nullable: true, description: undefined })
  id?: number | null;
  @Type(() => StandaloneWhereInput)
  @Field(() => [StandaloneWhereInput], {
    nullable: true,
    description: undefined,
  })
  AND?: Array<StandaloneWhereInput> | null;
  @Type(() => StandaloneWhereInput)
  @Field(() => [StandaloneWhereInput], {
    nullable: true,
    description: undefined,
  })
  OR?: Array<StandaloneWhereInput> | null;
  @Type(() => StandaloneWhereInput)
  @Field(() => [StandaloneWhereInput], {
    nullable: true,
    description: undefined,
  })
  NOT?: Array<StandaloneWhereInput> | null;
  @Type(() => DateTimeFilter)
  @Field(() => DateTimeFilter, { nullable: true, description: undefined })
  createdAt?: DateTimeFilter | null;
  @Type(() => DateTimeFilter)
  @Field(() => DateTimeFilter, { nullable: true, description: undefined })
  updatedAt?: DateTimeFilter | null;
  @Type(() => StringFilter)
  @Field(() => StringFilter, { nullable: true, description: undefined })
  name?: StringFilter | null;
  @Type(() => JsonFilter)
  @Field(() => JsonFilter, { nullable: true, description: undefined })
  jsonField?: JsonFilter | null;
  @Type(() => StringNullableListFilter)
  @Field(() => StringNullableListFilter, {
    nullable: true,
    description: undefined,
  })
  scalarList?: StringNullableListFilter | null;
}
