// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field } from '@nestjs/graphql';
import { GraphQLJSON } from 'graphql-scalars';
import { StandaloneCreatescalarListInput } from './standalone-createscalar-list.input';
import { Type } from 'class-transformer';

@InputType()
export class StandaloneCreateInput {
  @Field(() => Date, { nullable: true, description: undefined })
  createdAt?: Date | string | null;
  @Field(() => Date, { nullable: true, description: undefined })
  updatedAt?: Date | string | null;
  @Field(() => String, { nullable: false, description: undefined })
  name!: string;
  @Field(() => GraphQLJSON, { nullable: false, description: undefined })
  jsonField!: any;
  @Type(() => StandaloneCreatescalarListInput)
  @Field(() => StandaloneCreatescalarListInput, {
    nullable: true,
    description: undefined,
  })
  scalarList?: StandaloneCreatescalarListInput | null;
}
