// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field, Int } from '@nestjs/graphql';
import { GraphQLJSON } from 'graphql-scalars';
import type { JsonValue } from 'type-fest';
import { StandaloneCreatescalarListInput } from './standalone-createscalar-list.input';
import { Type } from 'class-transformer';

@InputType()
export class StandaloneCreateManyInput {
  @Field(() => Int, { nullable: true, description: undefined })
  id?: number | null;
  @Field(() => Date, { nullable: true, description: undefined })
  createdAt?: Date | string | null;
  @Field(() => Date, { nullable: true, description: undefined })
  updatedAt?: Date | string | null;
  @Field(() => String, { nullable: false, description: undefined })
  name!: string;
  @Field(() => GraphQLJSON, { nullable: false, description: undefined })
  jsonField!: JsonValue;
  @Type(() => StandaloneCreatescalarListInput)
  @Field(() => StandaloneCreatescalarListInput, {
    nullable: true,
    description: undefined,
  })
  scalarList?: StandaloneCreatescalarListInput | null;
}
