// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { ArgsType, Field } from '@nestjs/graphql';
import { CategoryCreateInput } from '../input/category-create.input';
import { Type } from 'class-transformer';

@ArgsType()
export class CategoryCreateArgs {
  @Type(() => CategoryCreateInput)
  @Field(() => CategoryCreateInput, { nullable: false, description: undefined })
  data!: CategoryCreateInput;
}
