// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { Type } from 'class-transformer';
import { IntFilter } from '../../../prisma/base/input/int-filter.input';
import { DateTimeFilter } from '../../../prisma/base/input/date-time-filter.input';
import { StringFilter } from '../../../prisma/base/input/string-filter.input';
import { JsonFilter } from '../../../prisma/base/input/json-filter.input';
import { JsonNullableListFilter } from '../../../prisma/base/input/json-nullable-list-filter.input';
import { StringNullableListFilter } from '../../../prisma/base/input/string-nullable-list-filter.input';
import { DecimalFilter } from '../../../prisma/base/input/decimal-filter.input';
import { DecimalNullableListFilter } from '../../../prisma/base/input/decimal-nullable-list-filter.input';
import { FloatFilter } from '../../../prisma/base/input/float-filter.input';
import { BytesFilter } from '../../../prisma/base/input/bytes-filter.input';
import { BytesNullableListFilter } from '../../../prisma/base/input/bytes-nullable-list-filter.input';
import { BigIntFilter } from '../../../prisma/base/input/big-int-filter.input';
import { BigIntNullableListFilter } from '../../../prisma/base/input/big-int-nullable-list-filter.input';
import { DateTimeNullableListFilter } from '../../../prisma/base/input/date-time-nullable-list-filter.input';

@InputType()
export class StandaloneModelWhereInput {
  @Type(() => StandaloneModelWhereInput)
  @Field(() => [StandaloneModelWhereInput], { nullable: true, description: undefined })
  AND?: Array<StandaloneModelWhereInput> | null;
  @Type(() => StandaloneModelWhereInput)
  @Field(() => [StandaloneModelWhereInput], { nullable: true, description: undefined })
  OR?: Array<StandaloneModelWhereInput> | null;
  @Type(() => StandaloneModelWhereInput)
  @Field(() => [StandaloneModelWhereInput], { nullable: true, description: undefined })
  NOT?: Array<StandaloneModelWhereInput> | null;
  @Type(() => IntFilter)
  @Field(() => IntFilter, { nullable: true, description: undefined })
  id?: IntFilter | null;
  @Type(() => DateTimeFilter)
  @Field(() => DateTimeFilter, { nullable: true, description: undefined })
  createdAt?: DateTimeFilter | null;
  @Type(() => DateTimeFilter)
  @Field(() => DateTimeFilter, { nullable: true, description: undefined })
  updatedAt?: DateTimeFilter | null;
  @Type(() => StringFilter)
  @Field(() => StringFilter, { nullable: true, description: undefined })
  name?: StringFilter | null;
  @Type(() => JsonFilter)
  @Field(() => JsonFilter, { nullable: true, description: undefined })
  jsonField?: JsonFilter | null;
  @Type(() => JsonNullableListFilter)
  @Field(() => JsonNullableListFilter, { nullable: true, description: undefined })
  jsonList?: JsonNullableListFilter | null;
  @Type(() => StringNullableListFilter)
  @Field(() => StringNullableListFilter, { nullable: true, description: undefined })
  stringList?: StringNullableListFilter | null;
  @Type(() => DecimalFilter)
  @Field(() => DecimalFilter, { nullable: true, description: undefined })
  decimalField?: DecimalFilter | null;
  @Type(() => DecimalNullableListFilter)
  @Field(() => DecimalNullableListFilter, { nullable: true, description: undefined })
  decimalList?: DecimalNullableListFilter | null;
  @Type(() => FloatFilter)
  @Field(() => FloatFilter, { nullable: true, description: undefined })
  floatField?: FloatFilter | null;
  @Type(() => BytesFilter)
  @Field(() => BytesFilter, { nullable: true, description: undefined })
  bytesField?: BytesFilter | null;
  @Type(() => BytesNullableListFilter)
  @Field(() => BytesNullableListFilter, { nullable: true, description: undefined })
  bytesList?: BytesNullableListFilter | null;
  @Type(() => BigIntFilter)
  @Field(() => BigIntFilter, { nullable: true, description: undefined })
  bigIntField?: BigIntFilter | null;
  @Type(() => BigIntNullableListFilter)
  @Field(() => BigIntNullableListFilter, { nullable: true, description: undefined })
  bigIntList?: BigIntNullableListFilter | null;
  @Type(() => DateTimeFilter)
  @Field(() => DateTimeFilter, { nullable: true, description: undefined })
  dateTimeField?: DateTimeFilter | null;
  @Type(() => DateTimeNullableListFilter)
  @Field(() => DateTimeNullableListFilter, { nullable: true, description: undefined })
  dateTimeList?: DateTimeNullableListFilter | null;
}
