// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { GraphQLBigInt } from 'graphql-scalars';

@InputType()
export class StandaloneModelCreatebigIntListInput {
  @Field(() => [GraphQLBigInt], { nullable: false, description: undefined })
  set!: Array<bigint> | Array<number>;
}
