// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { registerEnumType } from '@nestjs/graphql';

export enum StandaloneScalarFieldEnum {
  id = 'id',
  createdAt = 'createdAt',
  updatedAt = 'updatedAt',
  name = 'name',
  jsonField = 'jsonField',
  stringList = 'stringList',
  decimalField = 'decimalField',
  floatField = 'floatField',
  bytesField = 'bytesField',
  bigIntField = 'bigIntField',
  dateTimeField = 'dateTimeField',
}

registerEnumType(StandaloneScalarFieldEnum, {
  name: 'StandaloneScalarFieldEnum',
  description: undefined,
  valuesMap: undefined,
});
