// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { SortOrder } from '../../../prisma/base/enum/sort-order.enum';
import { PostOrderByRelationAggregateInput } from '../../../post/base/input/post-order-by-relation-aggregate.input';
import { Type } from 'class-transformer';
import { CategoryMetadataOrderByWithRelationInput } from '../../../category-metadata/base/input/category-metadata-order-by-with-relation.input';

@InputType()
export class CategoryOrderByWithRelationInput {
  @Field(() => SortOrder, { nullable: true, description: undefined })
  id?: keyof typeof SortOrder | null;
  @Field(() => SortOrder, { nullable: true, description: undefined })
  name?: keyof typeof SortOrder | null;
  @Field(() => SortOrder, { nullable: true, description: undefined })
  createdAt?: keyof typeof SortOrder | null;
  @Field(() => SortOrder, { nullable: true, description: undefined })
  updatedAt?: keyof typeof SortOrder | null;
  @Type(() => PostOrderByRelationAggregateInput)
  @Field(() => PostOrderByRelationAggregateInput, { nullable: true, description: undefined })
  posts?: PostOrderByRelationAggregateInput | null;
  @Type(() => CategoryMetadataOrderByWithRelationInput)
  @Field(() => CategoryMetadataOrderByWithRelationInput, { nullable: true, description: undefined })
  metadata?: CategoryMetadataOrderByWithRelationInput | null;
}
