// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { StringFieldUpdateOperationsInput } from '../../../prisma/base/input/string-field-update-operations.input';
import { Type } from 'class-transformer';
import { DateTimeFieldUpdateOperationsInput } from '../../../prisma/base/input/date-time-field-update-operations.input';
import { PostUpdateManyWithoutCategoriesNestedInput } from '../../../post/base/input/post-update-many-without-categories-nested.input';

@InputType()
export class CategoryUpdateWithoutMetadataInput {
  @Type(() => StringFieldUpdateOperationsInput)
  @Field(() => StringFieldUpdateOperationsInput, { nullable: true, description: undefined })
  name?: StringFieldUpdateOperationsInput | null;
  @Type(() => DateTimeFieldUpdateOperationsInput)
  @Field(() => DateTimeFieldUpdateOperationsInput, { nullable: true, description: undefined })
  createdAt?: DateTimeFieldUpdateOperationsInput | null;
  @Type(() => DateTimeFieldUpdateOperationsInput)
  @Field(() => DateTimeFieldUpdateOperationsInput, { nullable: true, description: undefined })
  updatedAt?: DateTimeFieldUpdateOperationsInput | null;
  @Type(() => PostUpdateManyWithoutCategoriesNestedInput)
  @Field(() => PostUpdateManyWithoutCategoriesNestedInput, { nullable: true, description: undefined })
  posts?: PostUpdateManyWithoutCategoriesNestedInput | null;
}
