// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { PostCreateNestedManyWithoutCategoriesInput } from '../../../post/base/input/post-create-nested-many-without-categories.input';
import { Type } from 'class-transformer';
import { CategoryMetadataCreateNestedOneWithoutCategoryInput } from '../../../category-metadata/base/input/category-metadata-create-nested-one-without-category.input';

@InputType()
export class CategoryCreateInput {
  @Field(() => String, { nullable: false, description: undefined })
  name!: string;
  @Field(() => Date, { nullable: true, description: undefined })
  createdAt?: Date | string | null;
  @Field(() => Date, { nullable: true, description: undefined })
  updatedAt?: Date | string | null;
  @Type(() => PostCreateNestedManyWithoutCategoriesInput)
  @Field(() => PostCreateNestedManyWithoutCategoriesInput, {
    nullable: true,
    description: undefined,
  })
  posts?: PostCreateNestedManyWithoutCategoriesInput | null;
  @Type(() => CategoryMetadataCreateNestedOneWithoutCategoryInput)
  @Field(() => CategoryMetadataCreateNestedOneWithoutCategoryInput, {
    nullable: true,
    description: undefined,
  })
  metadata?: CategoryMetadataCreateNestedOneWithoutCategoryInput | null;
}
