// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { ArgsType, Field } from '@nestjs/graphql';
import {
  CategoryMetadataUpdateManyMutationInput,
  CategoryMetadataWhereInput,
} from '../input';
import { Type } from 'class-transformer';

@ArgsType()
export class CategoryMetadataUpdateManyArgs {
  @Type(() => CategoryMetadataUpdateManyMutationInput)
  @Field(() => CategoryMetadataUpdateManyMutationInput, {
    nullable: false,
    description: undefined,
  })
  data!: CategoryMetadataUpdateManyMutationInput;
  @Type(() => CategoryMetadataWhereInput)
  @Field(() => CategoryMetadataWhereInput, {
    nullable: true,
    description: undefined,
  })
  where?: Omit<CategoryMetadataWhereInput, never> | null;
}
