// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { ArgsType, Field } from '@nestjs/graphql';
import { StandaloneUpdateInput, StandaloneWhereUniqueInput } from '../input';
import { Type } from 'class-transformer';
import { Prisma } from '../../../prisma-client';

@ArgsType()
export class StandaloneUpdateArgs {
  @Type(() => StandaloneUpdateInput)
  @Field(() => StandaloneUpdateInput, {
    nullable: false,
    description: undefined,
  })
  data!: StandaloneUpdateInput;
  @Type(() => StandaloneWhereUniqueInput)
  @Field(() => StandaloneWhereUniqueInput, {
    nullable: false,
    description: undefined,
  })
  where!: Prisma.AtLeast<StandaloneWhereUniqueInput, 'id'>;
}
