// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { ArgsType, Field } from '@nestjs/graphql';
import {
  StandaloneUpdateManyMutationInput,
  StandaloneWhereInput,
} from '../input';
import { Type } from 'class-transformer';

@ArgsType()
export class StandaloneUpdateManyArgs {
  @Type(() => StandaloneUpdateManyMutationInput)
  @Field(() => StandaloneUpdateManyMutationInput, {
    nullable: false,
    description: undefined,
  })
  data!: StandaloneUpdateManyMutationInput;
  @Type(() => StandaloneWhereInput)
  @Field(() => StandaloneWhereInput, { nullable: true, description: undefined })
  where?: Omit<StandaloneWhereInput, never> | null;
}
