// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { ArgsType, Field, Int } from '@nestjs/graphql';
import {
  StandaloneWhereInput,
  StandaloneOrderByWithRelationInput,
  StandaloneWhereUniqueInput,
} from '../input';
import { Type } from 'class-transformer';
import { Prisma } from '../../../@prisma-client';
import { StandaloneScalarFieldEnum } from '../enum';

@ArgsType()
export class StandaloneCountArgs {
  @Type(() => StandaloneWhereInput)
  @Field(() => StandaloneWhereInput, { nullable: true, description: undefined })
  where?: Omit<StandaloneWhereInput, never> | null;
  @Type(() => StandaloneOrderByWithRelationInput)
  @Field(() => [StandaloneOrderByWithRelationInput], {
    nullable: true,
    description: undefined,
  })
  orderBy?: Array<StandaloneOrderByWithRelationInput> | null;
  @Type(() => StandaloneWhereUniqueInput)
  @Field(() => StandaloneWhereUniqueInput, {
    nullable: true,
    description: undefined,
  })
  cursor?: Prisma.AtLeast<StandaloneWhereUniqueInput, 'id'>;
  @Field(() => Int, { nullable: true, description: undefined })
  take?: number | null;
  @Field(() => Int, { nullable: true, description: undefined })
  skip?: number | null;
  @Field(() => [StandaloneScalarFieldEnum], {
    nullable: true,
    description: undefined,
  })
  distinct?: Array<keyof typeof StandaloneScalarFieldEnum> | null;
}
