// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { ArgsType, Field } from '@nestjs/graphql';
import { UserCreateInput } from '../input';
import { Type } from 'class-transformer';

@ArgsType()
export class UserCreateArgs {
  @Type(() => UserCreateInput)
  @Field(() => UserCreateInput, { nullable: false, description: undefined })
  data!: UserCreateInput;
}
