// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { ArgsType, Field, Int } from '@nestjs/graphql';
import {
  UserWhereInput,
  UserOrderByWithRelationInput,
  UserWhereUniqueInput,
} from '../input';
import { Type } from 'class-transformer';
import { Prisma } from '../../../@prisma-client';
import { UserScalarFieldEnum } from '../enum';

@ArgsType()
export class UserCountArgs {
  @Type(() => UserWhereInput)
  @Field(() => UserWhereInput, { nullable: true, description: undefined })
  where?: Omit<UserWhereInput, never> | null;
  @Type(() => UserOrderByWithRelationInput)
  @Field(() => [UserOrderByWithRelationInput], {
    nullable: true,
    description: undefined,
  })
  orderBy?: Array<UserOrderByWithRelationInput> | null;
  @Type(() => UserWhereUniqueInput)
  @Field(() => UserWhereUniqueInput, { nullable: true, description: undefined })
  cursor?: Prisma.AtLeast<UserWhereUniqueInput, 'id' | 'email'>;
  @Field(() => Int, { nullable: true, description: undefined })
  take?: number | null;
  @Field(() => Int, { nullable: true, description: undefined })
  skip?: number | null;
  @Field(() => [UserScalarFieldEnum], {
    nullable: true,
    description: undefined,
  })
  distinct?: Array<keyof typeof UserScalarFieldEnum> | null;
}
