// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { CategoryCreateNestedOneWithoutMetadataInput } from './category-create-nested-one-without-metadata.input';
import { Type } from 'class-transformer';

@InputType()
export class CategoryMetadataCreateInput {
  @Field(() => Date, { nullable: true, description: undefined })
  createdAt?: Date | string;
  @Field(() => Date, { nullable: true, description: undefined })
  updatedAt?: Date | string;
  @Type(() => CategoryCreateNestedOneWithoutMetadataInput)
  @Field(() => CategoryCreateNestedOneWithoutMetadataInput, {
    nullable: false,
    description: undefined,
  })
  category!: Omit<CategoryCreateNestedOneWithoutMetadataInput, never>;
}
