// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field } from '@nestjs/graphql';
import { StringFieldUpdateOperationsInput } from './string-field-update-operations.input';
import { Type } from 'class-transformer';
import { DateTimeFieldUpdateOperationsInput } from './date-time-field-update-operations.input';
import { CategoryMetadataUpdateOneWithoutCategoryNestedInput } from './category-metadata-update-one-without-category-nested.input';

@InputType()
export class CategoryUpdateWithoutPostsInput {
  @Type(() => StringFieldUpdateOperationsInput)
  @Field(() => StringFieldUpdateOperationsInput, {
    nullable: true,
    description: undefined,
  })
  name?: StringFieldUpdateOperationsInput;
  @Type(() => DateTimeFieldUpdateOperationsInput)
  @Field(() => DateTimeFieldUpdateOperationsInput, {
    nullable: true,
    description: undefined,
  })
  createdAt?: DateTimeFieldUpdateOperationsInput;
  @Type(() => DateTimeFieldUpdateOperationsInput)
  @Field(() => DateTimeFieldUpdateOperationsInput, {
    nullable: true,
    description: undefined,
  })
  updatedAt?: DateTimeFieldUpdateOperationsInput;
  @Type(() => CategoryMetadataUpdateOneWithoutCategoryNestedInput)
  @Field(() => CategoryMetadataUpdateOneWithoutCategoryNestedInput, {
    nullable: true,
    description: undefined,
  })
  metadata?: Omit<CategoryMetadataUpdateOneWithoutCategoryNestedInput, never>;
}
