// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { PostCreateNestedManyWithoutCategoriesInput } from './post-create-nested-many-without-categories.input';
import { Type } from 'class-transformer';
import { CategoryMetadataCreateNestedOneWithoutCategoryInput } from './category-metadata-create-nested-one-without-category.input';

@InputType()
export class CategoryCreateInput {
  @Field(() => String, { nullable: false, description: undefined })
  name!: string;
  @Field(() => Date, { nullable: true, description: undefined })
  createdAt?: Date | string;
  @Field(() => Date, { nullable: true, description: undefined })
  updatedAt?: Date | string;
  @Type(() => PostCreateNestedManyWithoutCategoriesInput)
  @Field(() => PostCreateNestedManyWithoutCategoriesInput, {
    nullable: true,
    description: undefined,
  })
  posts?: Omit<PostCreateNestedManyWithoutCategoriesInput, never>;
  @Type(() => CategoryMetadataCreateNestedOneWithoutCategoryInput)
  @Field(() => CategoryMetadataCreateNestedOneWithoutCategoryInput, {
    nullable: true,
    description: undefined,
  })
  metadata?: Omit<CategoryMetadataCreateNestedOneWithoutCategoryInput, never>;
}
