// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { Type } from 'class-transformer';
import { IntFilter } from './int-filter.input';
import { StringFilter } from './string-filter.input';
import { DateTimeFilter } from './date-time-filter.input';

@InputType()
export class CategoryScalarWhereInput {
  @Type(() => CategoryScalarWhereInput)
  @Field(() => [CategoryScalarWhereInput], {
    nullable: true,
    description: undefined,
  })
  AND?: Array<CategoryScalarWhereInput>;
  @Type(() => CategoryScalarWhereInput)
  @Field(() => [CategoryScalarWhereInput], {
    nullable: true,
    description: undefined,
  })
  OR?: Array<CategoryScalarWhereInput>;
  @Type(() => CategoryScalarWhereInput)
  @Field(() => [CategoryScalarWhereInput], {
    nullable: true,
    description: undefined,
  })
  NOT?: Array<CategoryScalarWhereInput>;
  @Type(() => IntFilter)
  @Field(() => IntFilter, { nullable: true, description: undefined })
  id?: IntFilter;
  @Type(() => StringFilter)
  @Field(() => StringFilter, { nullable: true, description: undefined })
  name?: StringFilter;
  @Type(() => DateTimeFilter)
  @Field(() => DateTimeFilter, { nullable: true, description: undefined })
  createdAt?: DateTimeFilter;
  @Type(() => DateTimeFilter)
  @Field(() => DateTimeFilter, { nullable: true, description: undefined })
  updatedAt?: DateTimeFilter;
}
