// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field } from '@nestjs/graphql';
import { CategoryWhereInput } from './category-where.input';
import { Type } from 'class-transformer';
import { CategoryUpdateWithoutMetadataInput } from './category-update-without-metadata.input';

@InputType()
export class CategoryUpdateToOneWithWhereWithoutMetadataInput {
  @Type(() => CategoryWhereInput)
  @Field(() => CategoryWhereInput, { nullable: true, description: undefined })
  where?: Omit<CategoryWhereInput, never>;
  @Type(() => CategoryUpdateWithoutMetadataInput)
  @Field(() => CategoryUpdateWithoutMetadataInput, {
    nullable: false,
    description: undefined,
  })
  data!: CategoryUpdateWithoutMetadataInput;
}
