// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field, Int } from '@nestjs/graphql';
import { NestedIntNullableFilter } from './nested-int-nullable-filter.input';
import { Type } from 'class-transformer';

@InputType()
export class IntNullableFilter {
  @Field(() => Int, { nullable: true, description: undefined })
  equals?: number;
  @Field(() => [Int], { nullable: true, description: undefined })
  in?: Array<number>;
  @Field(() => [Int], { nullable: true, description: undefined })
  notIn?: Array<number>;
  @Field(() => Int, { nullable: true, description: undefined })
  lt?: number;
  @Field(() => Int, { nullable: true, description: undefined })
  lte?: number;
  @Field(() => Int, { nullable: true, description: undefined })
  gt?: number;
  @Field(() => Int, { nullable: true, description: undefined })
  gte?: number;
  @Type(() => NestedIntNullableFilter)
  @Field(() => NestedIntNullableFilter, {
    nullable: true,
    description: undefined,
  })
  not?: NestedIntNullableFilter;
}
