// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { JsonNullValueFilter } from '../enum';
import { GraphQLJSON } from 'graphql-scalars';

@InputType()
export class JsonFilter {
  @Field(() => JsonNullValueFilter, { nullable: true, description: undefined })
  equals?: keyof typeof JsonNullValueFilter;
  @Field(() => [String], { nullable: true, description: undefined })
  path?: Array<string>;
  @Field(() => String, { nullable: true, description: undefined })
  string_contains?: string;
  @Field(() => String, { nullable: true, description: undefined })
  string_starts_with?: string;
  @Field(() => String, { nullable: true, description: undefined })
  string_ends_with?: string;
  @Field(() => GraphQLJSON, { nullable: true, description: undefined })
  array_contains?: any;
  @Field(() => GraphQLJSON, { nullable: true, description: undefined })
  array_starts_with?: any;
  @Field(() => GraphQLJSON, { nullable: true, description: undefined })
  array_ends_with?: any;
  @Field(() => GraphQLJSON, { nullable: true, description: undefined })
  lt?: any;
  @Field(() => GraphQLJSON, { nullable: true, description: undefined })
  lte?: any;
  @Field(() => GraphQLJSON, { nullable: true, description: undefined })
  gt?: any;
  @Field(() => GraphQLJSON, { nullable: true, description: undefined })
  gte?: any;
  @Field(() => JsonNullValueFilter, { nullable: true, description: undefined })
  not?: keyof typeof JsonNullValueFilter;
}
