// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field, Int } from '@nestjs/graphql';
import { PostKind, JsonNullValueInput } from '../enum';
import { PostCreatescalarListInput } from './post-createscalar-list.input';
import { Type } from 'class-transformer';

@InputType()
export class PostCreateManyAuthorInput {
  @Field(() => Int, { nullable: true, description: undefined })
  id?: number;
  @Field(() => String, { nullable: false, description: undefined })
  title!: string;
  @Field(() => String, { nullable: true, description: undefined })
  content?: string;
  @Field(() => Boolean, { nullable: true, description: undefined })
  published?: boolean;
  @Field(() => Int, { nullable: false, description: undefined })
  anotherAuthorId!: number;
  @Field(() => Date, { nullable: true, description: undefined })
  createdAt?: Date | string;
  @Field(() => Date, { nullable: true, description: undefined })
  updatedAt?: Date | string;
  @Field(() => PostKind, { nullable: false, description: undefined })
  postKind!: keyof typeof PostKind;
  @Field(() => JsonNullValueInput, { nullable: false, description: undefined })
  jsonField!: keyof typeof JsonNullValueInput;
  @Type(() => PostCreatescalarListInput)
  @Field(() => PostCreatescalarListInput, {
    nullable: true,
    description: undefined,
  })
  scalarList?: PostCreatescalarListInput;
}
