// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field } from '@nestjs/graphql';
import { PostKind, JsonNullValueInput } from '../enum';
import { PostCreatescalarListInput } from './post-createscalar-list.input';
import { Type } from 'class-transformer';
import { UserCreateNestedOneWithoutPostsInput } from './user-create-nested-one-without-posts.input';
import { UserCreateNestedOneWithoutAnotherPostsInput } from './user-create-nested-one-without-another-posts.input';

@InputType()
export class PostCreateWithoutCategoriesInput {
  @Field(() => String, { nullable: false, description: undefined })
  title!: string;
  @Field(() => String, { nullable: true, description: undefined })
  content?: string;
  @Field(() => Boolean, { nullable: true, description: undefined })
  published?: boolean;
  @Field(() => Date, { nullable: true, description: undefined })
  createdAt?: Date | string;
  @Field(() => Date, { nullable: true, description: undefined })
  updatedAt?: Date | string;
  @Field(() => PostKind, { nullable: false, description: undefined })
  postKind!: keyof typeof PostKind;
  @Field(() => JsonNullValueInput, { nullable: false, description: undefined })
  jsonField!: keyof typeof JsonNullValueInput;
  @Type(() => PostCreatescalarListInput)
  @Field(() => PostCreatescalarListInput, {
    nullable: true,
    description: undefined,
  })
  scalarList?: PostCreatescalarListInput;
  @Type(() => UserCreateNestedOneWithoutPostsInput)
  @Field(() => UserCreateNestedOneWithoutPostsInput, {
    nullable: false,
    description: undefined,
  })
  author!: Omit<UserCreateNestedOneWithoutPostsInput, never>;
  @Type(() => UserCreateNestedOneWithoutAnotherPostsInput)
  @Field(() => UserCreateNestedOneWithoutAnotherPostsInput, {
    nullable: false,
    description: undefined,
  })
  anotherAuthor!: Omit<UserCreateNestedOneWithoutAnotherPostsInput, never>;
}
