// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field } from '@nestjs/graphql';
import { Type } from 'class-transformer';
import { IntFilter } from './int-filter.input';
import { StringFilter } from './string-filter.input';
import { StringNullableFilter } from './string-nullable-filter.input';
import { BoolFilter } from './bool-filter.input';
import { DateTimeFilter } from './date-time-filter.input';
import { EnumPostKindFilter } from './enum-post-kind-filter.input';
import { JsonFilter } from './json-filter.input';
import { StringNullableListFilter } from './string-nullable-list-filter.input';

@InputType()
export class PostScalarWhereInput {
  @Type(() => PostScalarWhereInput)
  @Field(() => [PostScalarWhereInput], {
    nullable: true,
    description: undefined,
  })
  AND?: Array<PostScalarWhereInput>;
  @Type(() => PostScalarWhereInput)
  @Field(() => [PostScalarWhereInput], {
    nullable: true,
    description: undefined,
  })
  OR?: Array<PostScalarWhereInput>;
  @Type(() => PostScalarWhereInput)
  @Field(() => [PostScalarWhereInput], {
    nullable: true,
    description: undefined,
  })
  NOT?: Array<PostScalarWhereInput>;
  @Type(() => IntFilter)
  @Field(() => IntFilter, { nullable: true, description: undefined })
  id?: IntFilter;
  @Type(() => StringFilter)
  @Field(() => StringFilter, { nullable: true, description: undefined })
  title?: StringFilter;
  @Type(() => StringNullableFilter)
  @Field(() => StringNullableFilter, { nullable: true, description: undefined })
  content?: StringNullableFilter;
  @Type(() => BoolFilter)
  @Field(() => BoolFilter, { nullable: true, description: undefined })
  published?: BoolFilter;
  @Type(() => IntFilter)
  @Field(() => IntFilter, { nullable: true, description: undefined })
  authorId?: IntFilter;
  @Type(() => IntFilter)
  @Field(() => IntFilter, { nullable: true, description: undefined })
  anotherAuthorId?: IntFilter;
  @Type(() => DateTimeFilter)
  @Field(() => DateTimeFilter, { nullable: true, description: undefined })
  createdAt?: DateTimeFilter;
  @Type(() => DateTimeFilter)
  @Field(() => DateTimeFilter, { nullable: true, description: undefined })
  updatedAt?: DateTimeFilter;
  @Type(() => EnumPostKindFilter)
  @Field(() => EnumPostKindFilter, { nullable: true, description: undefined })
  postKind?: EnumPostKindFilter;
  @Type(() => JsonFilter)
  @Field(() => JsonFilter, { nullable: true, description: undefined })
  jsonField?: JsonFilter;
  @Type(() => StringNullableListFilter)
  @Field(() => StringNullableListFilter, {
    nullable: true,
    description: undefined,
  })
  scalarList?: StringNullableListFilter;
}
