// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { PostCreateWithoutAuthorInput } from './post-create-without-author.input';
import { Type } from 'class-transformer';
import { PostCreateOrConnectWithoutAuthorInput } from './post-create-or-connect-without-author.input';
import { PostUpsertWithWhereUniqueWithoutAuthorInput } from './post-upsert-with-where-unique-without-author.input';
import { PostCreateManyAuthorInputEnvelope } from './post-create-many-author-input-envelope.input';
import { PostWhereUniqueInput } from './post-where-unique.input';
import { Prisma } from '../../prisma-client';
import { PostUpdateWithWhereUniqueWithoutAuthorInput } from './post-update-with-where-unique-without-author.input';
import { PostUpdateManyWithWhereWithoutAuthorInput } from './post-update-many-with-where-without-author.input';
import { PostScalarWhereInput } from './post-scalar-where.input';

@InputType()
export class PostUpdateManyWithoutAuthorNestedInput {
  @Type(() => PostCreateWithoutAuthorInput)
  @Field(() => [PostCreateWithoutAuthorInput], {
    nullable: true,
    description: undefined,
  })
  create?: Array<PostCreateWithoutAuthorInput>;
  @Type(() => PostCreateOrConnectWithoutAuthorInput)
  @Field(() => [PostCreateOrConnectWithoutAuthorInput], {
    nullable: true,
    description: undefined,
  })
  connectOrCreate?: Array<PostCreateOrConnectWithoutAuthorInput>;
  @Type(() => PostUpsertWithWhereUniqueWithoutAuthorInput)
  @Field(() => [PostUpsertWithWhereUniqueWithoutAuthorInput], {
    nullable: true,
    description: undefined,
  })
  upsert?: Array<PostUpsertWithWhereUniqueWithoutAuthorInput>;
  @Type(() => PostCreateManyAuthorInputEnvelope)
  @Field(() => PostCreateManyAuthorInputEnvelope, {
    nullable: true,
    description: undefined,
  })
  createMany?: PostCreateManyAuthorInputEnvelope;
  @Type(() => PostWhereUniqueInput)
  @Field(() => [PostWhereUniqueInput], {
    nullable: true,
    description: undefined,
  })
  set?: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostWhereUniqueInput)
  @Field(() => [PostWhereUniqueInput], {
    nullable: true,
    description: undefined,
  })
  disconnect?: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostWhereUniqueInput)
  @Field(() => [PostWhereUniqueInput], {
    nullable: true,
    description: undefined,
  })
  delete?: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostWhereUniqueInput)
  @Field(() => [PostWhereUniqueInput], {
    nullable: true,
    description: undefined,
  })
  connect?: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostUpdateWithWhereUniqueWithoutAuthorInput)
  @Field(() => [PostUpdateWithWhereUniqueWithoutAuthorInput], {
    nullable: true,
    description: undefined,
  })
  update?: Array<PostUpdateWithWhereUniqueWithoutAuthorInput>;
  @Type(() => PostUpdateManyWithWhereWithoutAuthorInput)
  @Field(() => [PostUpdateManyWithWhereWithoutAuthorInput], {
    nullable: true,
    description: undefined,
  })
  updateMany?: Array<PostUpdateManyWithWhereWithoutAuthorInput>;
  @Type(() => PostScalarWhereInput)
  @Field(() => [PostScalarWhereInput], {
    nullable: true,
    description: undefined,
  })
  deleteMany?: Array<PostScalarWhereInput>;
}
