// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field } from '@nestjs/graphql';
import { PostCreateWithoutAnotherAuthorInput } from './post-create-without-another-author.input';
import { Type } from 'class-transformer';
import { PostCreateOrConnectWithoutAnotherAuthorInput } from './post-create-or-connect-without-another-author.input';
import { PostUpsertWithWhereUniqueWithoutAnotherAuthorInput } from './post-upsert-with-where-unique-without-another-author.input';
import { PostCreateManyAnotherAuthorInputEnvelope } from './post-create-many-another-author-input-envelope.input';
import { PostWhereUniqueInput } from './post-where-unique.input';
import { Prisma } from '../../prisma-client';
import { PostUpdateWithWhereUniqueWithoutAnotherAuthorInput } from './post-update-with-where-unique-without-another-author.input';
import { PostUpdateManyWithWhereWithoutAnotherAuthorInput } from './post-update-many-with-where-without-another-author.input';
import { PostScalarWhereInput } from './post-scalar-where.input';

@InputType()
export class PostUpdateManyWithoutAnotherAuthorNestedInput {
  @Type(() => PostCreateWithoutAnotherAuthorInput)
  @Field(() => [PostCreateWithoutAnotherAuthorInput], {
    nullable: true,
    description: undefined,
  })
  create?: Array<PostCreateWithoutAnotherAuthorInput>;
  @Type(() => PostCreateOrConnectWithoutAnotherAuthorInput)
  @Field(() => [PostCreateOrConnectWithoutAnotherAuthorInput], {
    nullable: true,
    description: undefined,
  })
  connectOrCreate?: Array<PostCreateOrConnectWithoutAnotherAuthorInput>;
  @Type(() => PostUpsertWithWhereUniqueWithoutAnotherAuthorInput)
  @Field(() => [PostUpsertWithWhereUniqueWithoutAnotherAuthorInput], {
    nullable: true,
    description: undefined,
  })
  upsert?: Array<PostUpsertWithWhereUniqueWithoutAnotherAuthorInput>;
  @Type(() => PostCreateManyAnotherAuthorInputEnvelope)
  @Field(() => PostCreateManyAnotherAuthorInputEnvelope, {
    nullable: true,
    description: undefined,
  })
  createMany?: PostCreateManyAnotherAuthorInputEnvelope;
  @Type(() => PostWhereUniqueInput)
  @Field(() => [PostWhereUniqueInput], {
    nullable: true,
    description: undefined,
  })
  set?: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostWhereUniqueInput)
  @Field(() => [PostWhereUniqueInput], {
    nullable: true,
    description: undefined,
  })
  disconnect?: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostWhereUniqueInput)
  @Field(() => [PostWhereUniqueInput], {
    nullable: true,
    description: undefined,
  })
  delete?: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostWhereUniqueInput)
  @Field(() => [PostWhereUniqueInput], {
    nullable: true,
    description: undefined,
  })
  connect?: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostUpdateWithWhereUniqueWithoutAnotherAuthorInput)
  @Field(() => [PostUpdateWithWhereUniqueWithoutAnotherAuthorInput], {
    nullable: true,
    description: undefined,
  })
  update?: Array<PostUpdateWithWhereUniqueWithoutAnotherAuthorInput>;
  @Type(() => PostUpdateManyWithWhereWithoutAnotherAuthorInput)
  @Field(() => [PostUpdateManyWithWhereWithoutAnotherAuthorInput], {
    nullable: true,
    description: undefined,
  })
  updateMany?: Array<PostUpdateManyWithWhereWithoutAnotherAuthorInput>;
  @Type(() => PostScalarWhereInput)
  @Field(() => [PostScalarWhereInput], {
    nullable: true,
    description: undefined,
  })
  deleteMany?: Array<PostScalarWhereInput>;
}
