// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field } from '@nestjs/graphql';
import { DateTimeFieldUpdateOperationsInput } from './date-time-field-update-operations.input';
import { Type } from 'class-transformer';
import { StringFieldUpdateOperationsInput } from './string-field-update-operations.input';
import { JsonNullValueInput } from '../enum';
import { StandaloneUpdatescalarListInput } from './standalone-updatescalar-list.input';

@InputType()
export class StandaloneUpdateInput {
  @Type(() => DateTimeFieldUpdateOperationsInput)
  @Field(() => DateTimeFieldUpdateOperationsInput, {
    nullable: true,
    description: undefined,
  })
  createdAt?: DateTimeFieldUpdateOperationsInput;
  @Type(() => DateTimeFieldUpdateOperationsInput)
  @Field(() => DateTimeFieldUpdateOperationsInput, {
    nullable: true,
    description: undefined,
  })
  updatedAt?: DateTimeFieldUpdateOperationsInput;
  @Type(() => StringFieldUpdateOperationsInput)
  @Field(() => StringFieldUpdateOperationsInput, {
    nullable: true,
    description: undefined,
  })
  name?: StringFieldUpdateOperationsInput;
  @Field(() => JsonNullValueInput, { nullable: true, description: undefined })
  jsonField?: keyof typeof JsonNullValueInput;
  @Type(() => StandaloneUpdatescalarListInput)
  @Field(() => StandaloneUpdatescalarListInput, {
    nullable: true,
    description: undefined,
  })
  scalarList?: StandaloneUpdatescalarListInput;
}
