// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field } from '@nestjs/graphql';
import { Type } from 'class-transformer';
import { IntFilter } from './int-filter.input';
import { DateTimeFilter } from './date-time-filter.input';
import { StringFilter } from './string-filter.input';
import { JsonFilter } from './json-filter.input';
import { StringNullableListFilter } from './string-nullable-list-filter.input';

@InputType()
export class StandaloneWhereInput {
  @Type(() => StandaloneWhereInput)
  @Field(() => [StandaloneWhereInput], {
    nullable: true,
    description: undefined,
  })
  AND?: Array<StandaloneWhereInput>;
  @Type(() => StandaloneWhereInput)
  @Field(() => [StandaloneWhereInput], {
    nullable: true,
    description: undefined,
  })
  OR?: Array<StandaloneWhereInput>;
  @Type(() => StandaloneWhereInput)
  @Field(() => [StandaloneWhereInput], {
    nullable: true,
    description: undefined,
  })
  NOT?: Array<StandaloneWhereInput>;
  @Type(() => IntFilter)
  @Field(() => IntFilter, { nullable: true, description: undefined })
  id?: IntFilter;
  @Type(() => DateTimeFilter)
  @Field(() => DateTimeFilter, { nullable: true, description: undefined })
  createdAt?: DateTimeFilter;
  @Type(() => DateTimeFilter)
  @Field(() => DateTimeFilter, { nullable: true, description: undefined })
  updatedAt?: DateTimeFilter;
  @Type(() => StringFilter)
  @Field(() => StringFilter, { nullable: true, description: undefined })
  name?: StringFilter;
  @Type(() => JsonFilter)
  @Field(() => JsonFilter, { nullable: true, description: undefined })
  jsonField?: JsonFilter;
  @Type(() => StringNullableListFilter)
  @Field(() => StringNullableListFilter, {
    nullable: true,
    description: undefined,
  })
  scalarList?: StringNullableListFilter;
}
