// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field } from '@nestjs/graphql';

@InputType()
export class StringNullableListFilter {
  @Field(() => [String], { nullable: true, description: undefined })
  equals?: Array<string>;
  @Field(() => String, { nullable: true, description: undefined })
  has?: string;
  @Field(() => [String], { nullable: true, description: undefined })
  hasEvery?: Array<string>;
  @Field(() => [String], { nullable: true, description: undefined })
  hasSome?: Array<string>;
  @Field(() => Boolean, { nullable: true, description: undefined })
  isEmpty?: boolean;
}
