// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { InputType, Field, Int } from '@nestjs/graphql';
import { UserRole } from '../enum';

@InputType()
export class UserCreateManyParentInput {
  @Field(() => Int, { nullable: true, description: undefined })
  id?: number;
  @Field(() => String, { nullable: false, description: undefined })
  email!: string;
  @Field(() => String, { nullable: true, description: undefined })
  name?: string;
  @Field(() => UserRole, { nullable: true, description: undefined })
  role?: keyof typeof UserRole;
  @Field(() => Date, { nullable: true, description: undefined })
  createdAt?: Date | string;
  @Field(() => Date, { nullable: true, description: undefined })
  updatedAt?: Date | string;
  @Field(() => String, { nullable: false, description: undefined })
  toMapField!: string;
}
