// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { registerEnumType } from '@nestjs/graphql';

export enum CategoryMetadataScalarFieldEnum {
  id = 'id',
  categoryId = 'categoryId',
  createdAt = 'createdAt',
  updatedAt = 'updatedAt',
}

registerEnumType(CategoryMetadataScalarFieldEnum, {
  name: 'CategoryMetadataScalarFieldEnum',
  description: undefined,
});
