// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { registerEnumType } from '@nestjs/graphql';

/**
 *
 * Possible values:
 *   - BLOG // undefined
 *   - ADVERT // undefined
 */
export enum PostKind {
  BLOG = 'BLOG',
  ADVERT = 'ADVERT',
}

registerEnumType(PostKind, {
  name: 'PostKind',
  description:
    '\n\nPossible values:\n  - BLOG // undefined\n  - ADVERT // undefined',
});
