// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { registerEnumType } from '@nestjs/graphql';

export enum StandaloneScalarFieldEnum {
  id = 'id',
  createdAt = 'createdAt',
  updatedAt = 'updatedAt',
  name = 'name',
  jsonField = 'jsonField',
  scalarList = 'scalarList',
}

registerEnumType(StandaloneScalarFieldEnum, {
  name: 'StandaloneScalarFieldEnum',
  description: undefined,
});
