// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { GraphQLJSON } from 'graphql-scalars';
import type { JsonValue } from 'type-fest';

@InputType()
export class CategoryMetadataUpdatemetadataInput {
  @Field(() => [GraphQLJSON], { nullable: true, description: undefined })
  set?: Array<JsonValue> | null;
  @Field(() => [GraphQLJSON], { nullable: true, description: undefined })
  push?: Array<JsonValue> | null;
}
