// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { CategoryMetadataWhereInput } from './category-metadata-where.input';
import { Type } from 'class-transformer';
import { CategoryMetadataUpdateWithoutCategoryInput } from './category-metadata-update-without-category.input';

@InputType()
export class CategoryMetadataUpdateToOneWithWhereWithoutCategoryInput {
  @Type(() => CategoryMetadataWhereInput)
  @Field(() => CategoryMetadataWhereInput, {
    nullable: true,
    description: undefined,
  })
  where?: Omit<CategoryMetadataWhereInput, never> | null;
  @Type(() => CategoryMetadataUpdateWithoutCategoryInput)
  @Field(() => CategoryMetadataUpdateWithoutCategoryInput, {
    nullable: false,
    description: undefined,
  })
  data!: CategoryMetadataUpdateWithoutCategoryInput;
}
