// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { GraphQLJSON } from 'graphql-scalars';
import type { JsonValue } from 'type-fest';

@InputType()
export class CategoryMetadataCreatemetadataInput {
  @Field(() => [GraphQLJSON], { nullable: false, description: undefined })
  set!: Array<JsonValue>;
}
