// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { ArgsType, Field } from '@nestjs/graphql';
import { PostCreateInput } from '../input';
import { Type } from 'class-transformer';

@ArgsType()
export class PostCreateArgs {
  @Type(() => PostCreateInput)
  @Field(() => PostCreateInput, { nullable: false, description: undefined })
  data!: PostCreateInput;
}
