// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { ArgsType, Field } from '@nestjs/graphql';
import { StandaloneWhereUniqueInput } from '../input';
import { Type } from 'class-transformer';
import { Prisma } from '../../prisma-client';

@ArgsType()
export class StandaloneFindUniqueArgs {
  @Type(() => StandaloneWhereUniqueInput)
  @Field(() => StandaloneWhereUniqueInput, {
    nullable: false,
    description: undefined,
  })
  where!: Prisma.AtLeast<StandaloneWhereUniqueInput, 'id'>;
}
