// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { ArgsType, Field } from '@nestjs/graphql';
import { StandaloneWhereInput } from '../input';
import { Type } from 'class-transformer';

@ArgsType()
export class StandaloneDeleteManyArgs {
  @Type(() => StandaloneWhereInput)
  @Field(() => StandaloneWhereInput, { nullable: true, description: undefined })
  where?: Omit<StandaloneWhereInput, never>;
}
