// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { registerEnumType } from '@nestjs/graphql';

export enum UserScalarFieldEnum {
  id = 'id',
  email = 'email',
  name = 'name',
  role = 'role',
  createdAt = 'createdAt',
  updatedAt = 'updatedAt',
  parentId = 'parentId',
  mappedField = 'mappedField',
}

registerEnumType(UserScalarFieldEnum, {
  name: 'UserScalarFieldEnum',
  description: undefined,
  valuesMap: undefined,
});
