// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { registerEnumType } from '@nestjs/graphql';

export enum PostKind {
  BLOG = 'BLOG',
  ADVERT = 'ADVERT',
}

registerEnumType(PostKind, {
  name: 'PostKind',
  description: undefined,
  valuesMap: { BLOG: {}, ADVERT: {} },
});
