// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { GraphQLBigInt } from 'graphql-scalars';

@InputType()
export class BigIntNullableListFilter {
  @Field(() => [GraphQLBigInt], { nullable: true, description: undefined })
  equals?: Array<bigint> | Array<number> | null;
  @Field(() => GraphQLBigInt, { nullable: true, description: undefined })
  has?: bigint | number | null;
  @Field(() => [GraphQLBigInt], { nullable: true, description: undefined })
  hasEvery?: Array<bigint> | Array<number> | null;
  @Field(() => [GraphQLBigInt], { nullable: true, description: undefined })
  hasSome?: Array<bigint> | Array<number> | null;
  @Field(() => Boolean, { nullable: true, description: undefined })
  isEmpty?: boolean | null;
}
