// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { GraphQLByte } from 'graphql-scalars';

@InputType()
export class BytesFieldUpdateOperationsInput {
  @Field(() => GraphQLByte, { nullable: true, description: undefined })
  set?: Buffer | null;
}
