// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { GraphQLByte } from 'graphql-scalars';

@InputType()
export class BytesNullableListFilter {
  @Field(() => [GraphQLByte], { nullable: true, description: undefined })
  equals?: Array<Buffer> | null;
  @Field(() => GraphQLByte, { nullable: true, description: undefined })
  has?: Buffer | null;
  @Field(() => [GraphQLByte], { nullable: true, description: undefined })
  hasEvery?: Array<Buffer> | null;
  @Field(() => [GraphQLByte], { nullable: true, description: undefined })
  hasSome?: Array<Buffer> | null;
  @Field(() => Boolean, { nullable: true, description: undefined })
  isEmpty?: boolean | null;
}
