// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { InputType, Field } from '@nestjs/graphql';

@InputType()
export class DateTimeNullableListFilter {
  @Field(() => [Date], { nullable: true, description: undefined })
  equals?: Array<Date> | Array<string> | null;
  @Field(() => Date, { nullable: true, description: undefined })
  has?: Date | string | null;
  @Field(() => [Date], { nullable: true, description: undefined })
  hasEvery?: Array<Date> | Array<string> | null;
  @Field(() => [Date], { nullable: true, description: undefined })
  hasSome?: Array<Date> | Array<string> | null;
  @Field(() => Boolean, { nullable: true, description: undefined })
  isEmpty?: boolean | null;
}
