// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { NestedFloatFilter } from './nested-float-filter.input';
import { Type } from 'class-transformer';

@InputType()
export class FloatFilter {
  @Field(() => Number, { nullable: true, description: undefined })
  equals?: number | null;
  @Field(() => [Number], { nullable: true, description: undefined })
  in?: Array<number> | null;
  @Field(() => [Number], { nullable: true, description: undefined })
  notIn?: Array<number> | null;
  @Field(() => Number, { nullable: true, description: undefined })
  lt?: number | null;
  @Field(() => Number, { nullable: true, description: undefined })
  lte?: number | null;
  @Field(() => Number, { nullable: true, description: undefined })
  gt?: number | null;
  @Field(() => Number, { nullable: true, description: undefined })
  gte?: number | null;
  @Type(() => NestedFloatFilter)
  @Field(() => NestedFloatFilter, { nullable: true, description: undefined })
  not?: NestedFloatFilter | null;
}
