// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { InputType, Field } from '@nestjs/graphql';

@InputType()
export class FloatFieldUpdateOperationsInput {
  @Field(() => Number, { nullable: true, description: undefined })
  set?: number | null;
  @Field(() => Number, { nullable: true, description: undefined })
  increment?: number | null;
  @Field(() => Number, { nullable: true, description: undefined })
  decrement?: number | null;
  @Field(() => Number, { nullable: true, description: undefined })
  multiply?: number | null;
  @Field(() => Number, { nullable: true, description: undefined })
  divide?: number | null;
}
