// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { GraphQLJSON } from 'graphql-scalars';
import type { JsonValue } from 'type-fest';

@InputType()
export class JsonFilter {
  @Field(() => GraphQLJSON, { nullable: true, description: undefined })
  equals?: JsonValue | null;
  @Field(() => [String], { nullable: true, description: undefined })
  path?: Array<string> | null;
  @Field(() => String, { nullable: true, description: undefined })
  string_contains?: string | null;
  @Field(() => String, { nullable: true, description: undefined })
  string_starts_with?: string | null;
  @Field(() => String, { nullable: true, description: undefined })
  string_ends_with?: string | null;
  @Field(() => GraphQLJSON, { nullable: true, description: undefined })
  array_contains?: JsonValue | null;
  @Field(() => GraphQLJSON, { nullable: true, description: undefined })
  array_starts_with?: JsonValue | null;
  @Field(() => GraphQLJSON, { nullable: true, description: undefined })
  array_ends_with?: JsonValue | null;
  @Field(() => GraphQLJSON, { nullable: true, description: undefined })
  lt?: JsonValue | null;
  @Field(() => GraphQLJSON, { nullable: true, description: undefined })
  lte?: JsonValue | null;
  @Field(() => GraphQLJSON, { nullable: true, description: undefined })
  gt?: JsonValue | null;
  @Field(() => GraphQLJSON, { nullable: true, description: undefined })
  gte?: JsonValue | null;
  @Field(() => GraphQLJSON, { nullable: true, description: undefined })
  not?: JsonValue | null;
}
