// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { GraphQLJSON } from 'graphql-scalars';
import type { JsonValue } from 'type-fest';

@InputType()
export class JsonNullableListFilter {
  @Field(() => [GraphQLJSON], { nullable: true, description: undefined })
  equals?: Array<JsonValue> | null;
  @Field(() => GraphQLJSON, { nullable: true, description: undefined })
  has?: JsonValue | null;
  @Field(() => [GraphQLJSON], { nullable: true, description: undefined })
  hasEvery?: Array<JsonValue> | null;
  @Field(() => [GraphQLJSON], { nullable: true, description: undefined })
  hasSome?: Array<JsonValue> | null;
  @Field(() => Boolean, { nullable: true, description: undefined })
  isEmpty?: boolean | null;
}
