// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { InputType, Field } from '@nestjs/graphql';

@InputType()
export class StringFieldUpdateOperationsInput {
  @Field(() => String, { nullable: true, description: undefined })
  set?: string | null;
}
