// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { InputType, Field } from '@nestjs/graphql';

@InputType()
export class StringNullableListFilter {
  @Field(() => [String], { nullable: true, description: undefined })
  equals?: Array<string> | null;
  @Field(() => String, { nullable: true, description: undefined })
  has?: string | null;
  @Field(() => [String], { nullable: true, description: undefined })
  hasEvery?: Array<string> | null;
  @Field(() => [String], { nullable: true, description: undefined })
  hasSome?: Array<string> | null;
  @Field(() => Boolean, { nullable: true, description: undefined })
  isEmpty?: boolean | null;
}
