// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { ArgsType, Field } from '@nestjs/graphql';
import { CategoryMetadataUpdateManyMutationInput } from '../input/category-metadata-update-many-mutation.input';
import { Type } from 'class-transformer';
import { CategoryMetadataWhereInput } from '../input/category-metadata-where.input';

@ArgsType()
export class CategoryMetadataUpdateManyArgs {
  @Type(() => CategoryMetadataUpdateManyMutationInput)
  @Field(() => CategoryMetadataUpdateManyMutationInput, {
    nullable: false,
    description: undefined,
  })
  data!: CategoryMetadataUpdateManyMutationInput;
  @Type(() => CategoryMetadataWhereInput)
  @Field(() => CategoryMetadataWhereInput, {
    nullable: true,
    description: undefined,
  })
  where?: CategoryMetadataWhereInput | null;
}
