// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { ArgsType, Field } from '@nestjs/graphql';
import { UserUpdateManyMutationInput } from '../input/user-update-many-mutation.input';
import { Type } from 'class-transformer';
import { UserWhereInput } from '../input/user-where.input';

@ArgsType()
export class UserUpdateManyArgs {
  @Type(() => UserUpdateManyMutationInput)
  @Field(() => UserUpdateManyMutationInput, { nullable: false, description: undefined })
  data!: UserUpdateManyMutationInput;
  @Type(() => UserWhereInput)
  @Field(() => UserWhereInput, { nullable: true, description: undefined })
  where?: UserWhereInput | null;
}
