// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { ArgsType, Field } from '@nestjs/graphql';
import { UserCreateManyInput } from '../input/user-create-many.input';
import { Type } from 'class-transformer';

@ArgsType()
export class UserCreateManyArgs {
  @Type(() => UserCreateManyInput)
  @Field(() => [UserCreateManyInput], {
    nullable: false,
    description: undefined,
  })
  data!: Array<UserCreateManyInput>;
  @Field(() => Boolean, { nullable: true, description: undefined })
  skipDuplicates?: boolean | null;
}
