// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { ArgsType, Field } from '@nestjs/graphql';
import { UserCreateInput } from '../input/user-create.input';
import { Type } from 'class-transformer';

@ArgsType()
export class UserCreateArgs {
  @Type(() => UserCreateInput)
  @Field(() => UserCreateInput, { nullable: false, description: undefined })
  data!: UserCreateInput;
}
