// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { PrismaService } from '../../../prisma/prisma.service';
import { Prisma } from '../../../@prisma-client';
import { CategoryMetadata, Category } from '../model';
import { AffectedRowsOutput } from '../output';

export class CategoryMetadataBaseService {
  constructor(protected readonly prisma: PrismaService) {}

  async create(
    args: Prisma.CategoryMetadataCreateArgs
  ): Promise<CategoryMetadata> {
    return this.prisma.client.categoryMetadata.create(args);
  }

  async update(
    args: Prisma.CategoryMetadataUpdateArgs
  ): Promise<CategoryMetadata | null> {
    return this.prisma.client.categoryMetadata.update(args);
  }

  async delete(
    args: Prisma.CategoryMetadataDeleteArgs
  ): Promise<CategoryMetadata | null> {
    return this.prisma.client.categoryMetadata.delete(args);
  }

  async deleteMany(
    args: Prisma.CategoryMetadataDeleteManyArgs
  ): Promise<AffectedRowsOutput> {
    return this.prisma.client.categoryMetadata.deleteMany(args);
  }

  async findUnique(
    args: Prisma.CategoryMetadataFindUniqueArgs
  ): Promise<CategoryMetadata | null> {
    return this.prisma.client.categoryMetadata.findUnique(args);
  }

  async findMany(
    args: Prisma.CategoryMetadataFindManyArgs
  ): Promise<Array<CategoryMetadata>> {
    return this.prisma.client.categoryMetadata.findMany(args);
  }

  resolveCategory(parent: CategoryMetadata): Promise<Category> {
    return this.prisma.client.categoryMetadata
      .findUniqueOrThrow({
        where: { id: parent.id },
      })
      .category();
  }

  count(args: Prisma.CategoryMetadataCountArgs): Promise<number> {
    return this.prisma.client.categoryMetadata.count(args);
  }
}
