// This file is generated by @nest-ease/generator. DO NOT MODIFY!
/* eslint-disable @typescript-eslint/no-explicit-any */
import { PrismaService } from '../../../prisma/prisma.service';
import { User, Post } from '../model';
import {
  UserCreateArgs,
  UserUpdateArgs,
  UserDeleteArgs,
  UserDeleteManyArgs,
  UserFindUniqueArgs,
  UserFindManyArgs,
  PostFindManyArgs,
} from '../args';
import { AffectedRowsOutput } from '../output';

export class UserBaseService {
  constructor(protected readonly prisma: PrismaService) {}

  async create(args: UserCreateArgs): Promise<User> {
    return this.prisma.client.user.create(args);
  }

  async update(args: UserUpdateArgs): Promise<User | null> {
    return this.prisma.client.user.update(args);
  }

  async delete(args: UserDeleteArgs): Promise<User | null> {
    return this.prisma.client.user.delete(args);
  }

  async deleteMany(args: UserDeleteManyArgs): Promise<AffectedRowsOutput> {
    return this.prisma.client.user.deleteMany(args);
  }

  async findUnique(args: UserFindUniqueArgs): Promise<User | null> {
    return this.prisma.client.user.findUnique(args);
  }

  async findMany(args: UserFindManyArgs): Promise<Array<User>> {
    return this.prisma.client.user.findMany(args);
  }

  count(args: UserFindManyArgs): Promise<number> {
    return this.prisma.client.user.count(args);
  }

  resolvePosts(parent: User, args: PostFindManyArgs): Promise<Array<Post>> {
    return this.prisma.client.user
      .findUniqueOrThrow({
        where: {
          id: parent.id,
        },
      })
      .posts(args);
  }

  resolveParent(parent: User): Promise<User | null> {
    return this.prisma.client.user
      .findUniqueOrThrow({
        where: {
          id: parent.id,
        },
      })
      .parent();
  }

  resolveChildren(parent: User, args: UserFindManyArgs): Promise<Array<User>> {
    return this.prisma.client.user
      .findUniqueOrThrow({
        where: {
          id: parent.id,
        },
      })
      .children(args);
  }

  resolveAnotherPosts(
    parent: User,
    args: PostFindManyArgs
  ): Promise<Array<Post>> {
    return this.prisma.client.user
      .findUniqueOrThrow({
        where: {
          id: parent.id,
        },
      })
      .anotherPosts(args);
  }
}
