// This file is generated by @nest-ease/generator. DO NOT MANUALLY MODIFY!
import { InputType, Field, HideField } from '@nestjs/graphql';
import { PostCreateWithoutAnotherAuthorInput } from './post-create-without-another-author.input';
import { Type } from 'class-transformer';
import { PostCreateOrConnectWithoutAnotherAuthorInput } from './post-create-or-connect-without-another-author.input';
import { PostUpsertWithWhereUniqueWithoutAnotherAuthorInput } from './post-upsert-with-where-unique-without-another-author.input';
import { PostCreateManyAnotherAuthorInputEnvelope } from './post-create-many-another-author-input-envelope.input';
import { PostWhereUniqueInput } from './post-where-unique.input';
import { Prisma } from '../../../@prisma-client';
import { PostUpdateWithWhereUniqueWithoutAnotherAuthorInput } from './post-update-with-where-unique-without-another-author.input';
import { PostUpdateManyWithWhereWithoutAnotherAuthorInput } from './post-update-many-with-where-without-another-author.input';
import { PostScalarWhereInput } from './post-scalar-where.input';

@InputType()
export class PostUpdateManyWithoutAnotherAuthorNestedInput {
  @Type(() => PostCreateWithoutAnotherAuthorInput)
  @Field(() => [PostCreateWithoutAnotherAuthorInput], { nullable: true, description: undefined })
  create?: Array<PostCreateWithoutAnotherAuthorInput> | null;
  @Type(() => PostCreateOrConnectWithoutAnotherAuthorInput)
  @HideField()
  connectOrCreate?: Array<PostCreateOrConnectWithoutAnotherAuthorInput> | null;
  @Type(() => PostUpsertWithWhereUniqueWithoutAnotherAuthorInput)
  @HideField()
  upsert?: Array<PostUpsertWithWhereUniqueWithoutAnotherAuthorInput> | null;
  @Type(() => PostCreateManyAnotherAuthorInputEnvelope)
  @HideField()
  createMany?: PostCreateManyAnotherAuthorInputEnvelope | null;
  @Type(() => PostWhereUniqueInput)
  @HideField()
  set?: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostWhereUniqueInput)
  @Field(() => [PostWhereUniqueInput], { nullable: true, description: undefined })
  disconnect?: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostWhereUniqueInput)
  @Field(() => [PostWhereUniqueInput], { nullable: true, description: undefined })
  delete?: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostWhereUniqueInput)
  @Field(() => [PostWhereUniqueInput], { nullable: true, description: undefined })
  connect?: Prisma.AtLeast<PostWhereUniqueInput, 'id'>;
  @Type(() => PostUpdateWithWhereUniqueWithoutAnotherAuthorInput)
  @Field(() => [PostUpdateWithWhereUniqueWithoutAnotherAuthorInput], { nullable: true, description: undefined })
  update?: Array<PostUpdateWithWhereUniqueWithoutAnotherAuthorInput> | null;
  @Type(() => PostUpdateManyWithWhereWithoutAnotherAuthorInput)
  @HideField()
  updateMany?: Array<PostUpdateManyWithWhereWithoutAnotherAuthorInput> | null;
  @Type(() => PostScalarWhereInput)
  @HideField()
  deleteMany?: Array<PostScalarWhereInput> | null;
}
