// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { PostCreateManyAuthorInput } from './post-create-many-author.input';
import { Type } from 'class-transformer';

@InputType()
export class PostCreateManyAuthorInputEnvelope {
  @Type(() => PostCreateManyAuthorInput)
  @Field(() => [PostCreateManyAuthorInput], { nullable: false, description: undefined })
  data!: Array<PostCreateManyAuthorInput>;
  @Field(() => Boolean, { nullable: true, description: undefined })
  skipDuplicates?: boolean | null;
}
