// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { InputType, Field } from '@nestjs/graphql';
import { PostKind } from '../enum/post-kind.enum';
import { GraphQLJSON } from 'graphql-scalars';
import type { JsonValue } from 'type-fest';
import { PostCreatescalarListInput } from './post-createscalar-list.input';
import { Type } from 'class-transformer';
import { UserCreateNestedOneWithoutPostsInput } from '../../../user/base/input/user-create-nested-one-without-posts.input';
import { CategoryCreateNestedManyWithoutPostsInput } from '../../../category/base/input/category-create-nested-many-without-posts.input';

@InputType()
export class PostCreateWithoutAnotherAuthorInput {
  @Field(() => String, { nullable: false, description: undefined })
  title!: string;
  @Field(() => String, { nullable: true, description: undefined })
  content?: string | null;
  @Field(() => Boolean, { nullable: true, description: undefined })
  published?: boolean | null;
  @Field(() => Date, { nullable: true, description: undefined })
  createdAt?: Date | string | null;
  @Field(() => Date, { nullable: true, description: undefined })
  updatedAt?: Date | string | null;
  @Field(() => PostKind, { nullable: false, description: undefined })
  postKind!: keyof typeof PostKind;
  @Field(() => GraphQLJSON, { nullable: false, description: undefined })
  jsonField!: JsonValue;
  @Type(() => PostCreatescalarListInput)
  @Field(() => PostCreatescalarListInput, {
    nullable: true,
    description: undefined,
  })
  scalarList?: PostCreatescalarListInput | null;
  @Type(() => UserCreateNestedOneWithoutPostsInput)
  @Field(() => UserCreateNestedOneWithoutPostsInput, {
    nullable: false,
    description: undefined,
  })
  author!: Omit<UserCreateNestedOneWithoutPostsInput, never>;
  @Type(() => CategoryCreateNestedManyWithoutPostsInput)
  @Field(() => CategoryCreateNestedManyWithoutPostsInput, {
    nullable: true,
    description: undefined,
  })
  categories?: Omit<CategoryCreateNestedManyWithoutPostsInput, never> | null;
}
