// This file is generated by @nest-ease/generator. DO NOT MODIFY!
import { registerEnumType } from '@nestjs/graphql';

export enum StandaloneModelScalarFieldEnum {
  id = 'id',
  createdAt = 'createdAt',
  updatedAt = 'updatedAt',
  name = 'name',
  jsonField = 'jsonField',
  jsonList = 'jsonList',
  stringList = 'stringList',
  decimalField = 'decimalField',
  decimalList = 'decimalList',
  floatField = 'floatField',
  bytesField = 'bytesField',
  bytesList = 'bytesList',
  bigIntField = 'bigIntField',
  bigIntList = 'bigIntList',
  dateTimeField = 'dateTimeField',
  dateTimeList = 'dateTimeList'
}

registerEnumType(StandaloneModelScalarFieldEnum, { name: 'StandaloneModelScalarFieldEnum', description: undefined, valuesMap: undefined })
