// This file is generated by @nest-ease/generator. DO NOT MODIFY!
export * from './category-base.resolver';
export * from './category-metadata-base.resolver';
export * from './post-base.resolver';
export * from './standalone-base.resolver';
export * from './user-base.resolver';
